/**
 * Payroll MIS downloads — Excel (values, not formulas), PDF and CSV.
 * Every file starts with the report header: company, report, period, filters, generated on / by.
 *
 * A report is described as:
 *   { title, sheets: [{ name, columns: [{ label, kind }], rows: [{ cells: [...], total?, tone? }] }] }
 * kind: 'text' | 'money' | 'count' | 'pct' | 'date'. Money cells are whole rupees on screen and in
 * PDF / CSV; Excel keeps the stored 2-decimal value with a whole-rupee number format.
 */
import ExcelJS from 'exceljs';
import jsPDF from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import { MASKED_SECRET, salaryFiguresHidden } from '../salaryPrivacy';
import { formatChangePct, formatCount, formatInr } from './misMetrics';

export function reportHeaderLines(header) {
  return [
    ['Company', header.company || ''],
    ['Report', header.report || ''],
    ['Period', header.period || ''],
    ['Filters', header.filters || 'None'],
    ['Generated on', header.generatedOn || ''],
    ['Generated by', header.generatedBy || ''],
  ];
}

function displayCell(value, kind, hidden) {
  if (value === null || value === undefined || value === '') return kind === 'pct' ? '' : value ?? '';
  if (typeof value === 'string' && kind !== 'pct') return value;
  if (kind === 'money') return hidden ? MASKED_SECRET : formatInr(value);
  if (kind === 'count') return formatCount(value);
  if (kind === 'pct') return typeof value === 'string' ? value : formatChangePct(value);
  return String(value);
}

function fileStem(title, period) {
  return `${title} ${period}`.replace(/[^\w\- ]+/g, '').trim().replace(/\s+/g, '_');
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.setTimeout(() => URL.revokeObjectURL(url), 1500);
  return filename;
}

export async function exportReportExcel(report, header) {
  const hidden = salaryFiguresHidden();
  const wb = new ExcelJS.Workbook();
  wb.creator = header.company || 'ERP';
  wb.created = new Date();
  for (const sheet of report.sheets) {
    const ws = wb.addWorksheet(String(sheet.name || 'Report').slice(0, 31));
    for (const [k, v] of reportHeaderLines(header)) {
      const row = ws.addRow([k, v]);
      row.getCell(1).font = { bold: true, size: 9 };
      row.getCell(2).font = { size: 9 };
    }
    ws.addRow([]);
    const headRow = ws.addRow(sheet.columns.map((c) => c.label));
    headRow.height = 26;
    headRow.eachCell((cell) => {
      cell.font = { bold: true, size: 9 };
      cell.alignment = { wrapText: true, vertical: 'middle', horizontal: 'center' };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEEF2F6' } };
    });
    for (const r of sheet.rows) {
      const values = sheet.columns.map((c, i) => {
        const v = r.cells[i];
        if (c.kind === 'money' && typeof v === 'number') return hidden ? MASKED_SECRET : v;
        if (c.kind === 'count' && typeof v === 'number') return v;
        if (c.kind === 'pct') return displayCell(v, 'pct', hidden);
        return v ?? '';
      });
      const row = ws.addRow(values);
      sheet.columns.forEach((c, i) => {
        const cell = row.getCell(i + 1);
        cell.font = { size: 9, bold: !!r.total };
        if (c.kind === 'money') cell.numFmt = '#,##,##0';
        if (c.kind !== 'text') cell.alignment = { horizontal: 'right' };
      });
    }
    sheet.columns.forEach((c, i) => {
      ws.getColumn(i + 1).width = c.kind === 'text' ? Math.max(14, Math.min(40, c.label.length + 6)) : 15;
    });
  }
  const buffer = await wb.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  return triggerDownload(blob, `${fileStem(report.title, header.period)}.xlsx`);
}

export function exportReportPdf(report, header) {
  const hidden = salaryFiguresHidden();
  const wide = report.sheets.some((s) => s.columns.length > 6);
  const doc = new jsPDF({ orientation: wide ? 'landscape' : 'portrait', unit: 'mm', format: 'a4' });
  const margin = 12;
  let first = true;
  for (const sheet of report.sheets) {
    if (!first) doc.addPage();
    first = false;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text(header.company || '', margin, margin + 2);
    doc.setFontSize(11);
    doc.text(`${header.report}${report.sheets.length > 1 ? ` — ${sheet.name}` : ''}`, margin, margin + 9);
    autoTable(doc, {
      startY: margin + 13,
      margin: { left: margin, right: margin },
      theme: 'plain',
      styles: { fontSize: 8, cellPadding: 0.8 },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 28 } },
      body: reportHeaderLines(header).slice(2),
    });
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 4,
      margin: { left: margin, right: margin },
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 1.4, textColor: [33, 37, 41] },
      headStyles: { fillColor: [238, 242, 246], textColor: [33, 37, 41], fontStyle: 'bold' },
      head: [sheet.columns.map((c) => ({ content: c.label, styles: { halign: c.kind === 'text' ? 'left' : 'right' } }))],
      body: sheet.rows.map((r) => sheet.columns.map((c, i) => ({
        content: displayCell(r.cells[i], c.kind, hidden),
        styles: {
          halign: c.kind === 'text' ? 'left' : 'right',
          fontStyle: r.total ? 'bold' : 'normal',
          ...(r.tones?.[i] === 'bad' ? { textColor: [185, 28, 28] } : {}),
          ...(r.tones?.[i] === 'good' ? { textColor: [21, 128, 61] } : {}),
          ...(r.tones?.[i] === 'warn' ? { textColor: [180, 83, 9] } : {}),
        },
      }))),
    });
  }
  const blob = doc.output('blob');
  return triggerDownload(blob, `${fileStem(report.title, header.period)}.pdf`);
}

function csvEscape(v) {
  const s = v === null || v === undefined ? '' : String(v);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function reportCsvText(report, header) {
  const hidden = salaryFiguresHidden();
  const lines = reportHeaderLines(header).map((pair) => pair.map(csvEscape).join(','));
  for (const sheet of report.sheets) {
    lines.push('');
    if (report.sheets.length > 1) lines.push(csvEscape(sheet.name));
    lines.push(sheet.columns.map((c) => csvEscape(c.label)).join(','));
    for (const r of sheet.rows) {
      lines.push(sheet.columns.map((c, i) => {
        const v = r.cells[i];
        if (c.kind === 'money' && typeof v === 'number') return hidden ? MASKED_SECRET : Math.round(v);
        if (c.kind === 'pct') return csvEscape(displayCell(v, 'pct', hidden));
        return csvEscape(v);
      }).join(','));
    }
  }
  return `\uFEFF${lines.join('\r\n')}`;
}

export function exportReportCsv(report, header) {
  const blob = new Blob([reportCsvText(report, header)], { type: 'text/csv;charset=utf-8' });
  return triggerDownload(blob, `${fileStem(report.title, header.period)}.csv`);
}
