-- Consolidated Supabase SQL migrations
-- Generated by combining all files from supabase/migrations in timestamp order.
-- Run from top to bottom.

-- =============================================================================
-- BEGIN: 20250220000000_profiles_for_roles.sql
-- =============================================================================
-- Profiles table: stores role, team, and allowed_modules for each user.
-- Used for listing users in Admin User Management and as source of truth for access.
--
-- IMPORTANT: Run this entire file in Supabase Dashboard -> SQL Editor to create
-- the table and RLS. The app uses user_metadata for roles until you enable profiles:
--   - To avoid 500 on /rest/v1/profiles, leave VITE_USE_PROFILES_TABLE unset (default).
--   - After this migration runs successfully, set VITE_USE_PROFILES_TABLE=true in .env
--     and restart the app to use the profiles table for roles and User Management.
-- If 500 persists after running this, check Dashboard -> Logs (Postgres / API) for the real error.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  username text,
  team text,
  role text,
  allowed_modules jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- RLS
alter table public.profiles enable row level security;

-- Drop policies if they exist (safe to re-run this migration)
drop policy if exists "Users can read own profile" on public.profiles;
drop policy if exists "Admins can read all profiles" on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;
drop policy if exists "Admins can update any profile" on public.profiles;

-- Users can read their own profile
create policy "Users can read own profile"
  on public.profiles for select
  using (id = auth.uid());

-- Admins can read all profiles (admin = role in their own profile)
create policy "Admins can read all profiles"
  on public.profiles for select
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- Users can insert their own profile (e.g. on signup)
create policy "Users can insert own profile"
  on public.profiles for insert
  with check (id = auth.uid());

-- Users can update their own profile (e.g. username only if you allow)
create policy "Users can update own profile"
  on public.profiles for update
  using (id = auth.uid());

-- Admins can update any profile (for User Management edit access)
create policy "Admins can update any profile"
  on public.profiles for update
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- Optional: keep updated_at in sync
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- Optional: comment for clarity
comment on table public.profiles is 'User profiles: role, team, allowed_modules. Source of truth for role-based access.';

-- =============================================================================
-- BEGIN: 20250312100000_billing_public_tables.sql
-- =============================================================================
-- BILLING MODULE: All tables in BILLING schema (billing.po_wo, billing.invoice, etc.)
-- App hits via: supabase.schema('billing').from('po_wo') - same pattern as other modules.
-- In Supabase Dashboard -> Settings -> API -> Exposed schemas, add: billing
-- If you see "new row violates row-level security", run the CREATE OR REPLACE FUNCTION
-- billing.current_user_has_billing_access() block in SQL Editor to refresh it.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS billing;

-- Helper: current user has billing or admin access (used in RLS)
-- Allow when: profile has role admin/billing, team=billing, or allowed_modules contains billing.
-- Allow when: no profile row or profile with null role/team (so billing works before/without profile setup).
CREATE OR REPLACE FUNCTION billing.current_user_has_billing_access()
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  has_access boolean;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid()
      AND (p.role = 'admin' OR p.role = 'billing' OR p.team = 'billing'
           OR (p.allowed_modules IS NOT NULL AND p.allowed_modules @> '"billing"'::jsonb))
  ) INTO has_access;
  IF has_access THEN RETURN true; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid()) THEN RETURN true; END IF;
  IF EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.role IS NULL AND p.team IS NULL
      AND (p.allowed_modules IS NULL OR p.allowed_modules = '[]'::jsonb)
  ) THEN RETURN true; END IF;
  RETURN false;
END;
$$;

COMMENT ON FUNCTION billing.current_user_has_billing_access() IS
  'Returns true if current user has billing access (role/team/allowed_modules), or no profile / unset profile. Used by RLS on billing.* tables.';

GRANT EXECUTE ON FUNCTION billing.current_user_has_billing_access() TO authenticated;

-- 1. PO/WO (billing.po_wo)
CREATE TABLE IF NOT EXISTS billing.po_wo (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id text NOT NULL DEFAULT '',
  location_name text,
  legal_name text NOT NULL DEFAULT '',
  billing_address text,
  gstin text,
  current_coordinator text,
  contact_number text,
  oc_number text,
  oc_series text,
  vertical text DEFAULT 'MANP',
  po_wo_number text,
  po_quantity numeric(18,2) DEFAULT 0,
  total_contract_value numeric(18,2) DEFAULT 0,
  sac_code text DEFAULT '9985',
  hsn_code text,
  service_description text,
  start_date date,
  end_date date,
  billing_type text DEFAULT 'Monthly',
  billing_cycle integer DEFAULT 30,
  payment_terms text,
  revised_po boolean DEFAULT false,
  renewal_pending boolean DEFAULT false,
  status text DEFAULT 'active',
  approval_status text DEFAULT 'draft',
  approval_sent_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_billing_po_wo_oc_number ON billing.po_wo(oc_number);
CREATE INDEX IF NOT EXISTS idx_billing_po_wo_status ON billing.po_wo(status);
CREATE INDEX IF NOT EXISTS idx_billing_po_wo_approval_status ON billing.po_wo(approval_status);

COMMENT ON TABLE billing.po_wo IS 'PO/WO Management - contract master for Billing.';

-- 2. PO Rate Category (billing.po_rate_category)
CREATE TABLE IF NOT EXISTS billing.po_rate_category (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  po_id uuid NOT NULL REFERENCES billing.po_wo(id) ON DELETE CASCADE,
  description text NOT NULL,
  rate numeric(18,2) NOT NULL DEFAULT 0,
  sort_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_billing_po_rate_category_po_id ON billing.po_rate_category(po_id);

-- 3. Contact Log (billing.po_contact_log)
CREATE TABLE IF NOT EXISTS billing.po_contact_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  po_id uuid NOT NULL REFERENCES billing.po_wo(id) ON DELETE CASCADE,
  contact_name text NOT NULL,
  contact_number text,
  from_date date,
  to_date date,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_billing_po_contact_log_po_id ON billing.po_contact_log(po_id);

-- 4. Invoice (billing.invoice)
CREATE TABLE IF NOT EXISTS billing.invoice (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  po_id uuid REFERENCES billing.po_wo(id) ON DELETE SET NULL,
  site_id text,
  tax_invoice_number text NOT NULL,
  invoice_date date NOT NULL,
  client_legal_name text,
  client_address text,
  gstin text,
  oc_number text,
  po_wo_number text,
  billing_type text DEFAULT 'Monthly',
  hsn_sac text,
  taxable_value numeric(18,2) DEFAULT 0,
  cgst_rate numeric(5,2) DEFAULT 9,
  sgst_rate numeric(5,2) DEFAULT 9,
  cgst_amt numeric(18,2) DEFAULT 0,
  sgst_amt numeric(18,2) DEFAULT 0,
  calculated_invoice_amount numeric(18,2) DEFAULT 0,
  total_amount numeric(18,2) DEFAULT 0,
  pa_status text DEFAULT 'Pending',
  payment_status boolean DEFAULT false,
  pending_amount numeric(18,2),
  payment_terms text,
  e_invoice_irn text,
  e_invoice_ack_no text,
  e_invoice_ack_dt text,
  e_invoice_signed_qr text,
  less_more_billing numeric(18,2),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_billing_invoice_tax_number ON billing.invoice(tax_invoice_number);
CREATE INDEX IF NOT EXISTS idx_billing_invoice_po_id ON billing.invoice(po_id);
CREATE INDEX IF NOT EXISTS idx_billing_invoice_date ON billing.invoice(invoice_date);

-- 5. Invoice Line Item (billing.invoice_line_item)
CREATE TABLE IF NOT EXISTS billing.invoice_line_item (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL REFERENCES billing.invoice(id) ON DELETE CASCADE,
  line_order integer NOT NULL DEFAULT 0,
  description text NOT NULL,
  hsn_sac text,
  quantity numeric(18,2) NOT NULL DEFAULT 0,
  rate numeric(18,2) NOT NULL DEFAULT 0,
  amount numeric(18,2) NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_billing_invoice_line_item_invoice_id ON billing.invoice_line_item(invoice_id);

-- 6. Invoice Attachment (billing.invoice_attachment)
CREATE TABLE IF NOT EXISTS billing.invoice_attachment (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL REFERENCES billing.invoice(id) ON DELETE CASCADE,
  attachment_type text NOT NULL,
  name text,
  url text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_billing_invoice_attachment_invoice_id ON billing.invoice_attachment(invoice_id);

-- 7. Credit / Debit Note (billing.credit_debit_note)
CREATE TABLE IF NOT EXISTS billing.credit_debit_note (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_invoice_id uuid REFERENCES billing.invoice(id) ON DELETE SET NULL,
  parent_tax_invoice_number text,
  note_type text NOT NULL CHECK (note_type IN ('credit', 'debit')),
  amount numeric(18,2) NOT NULL DEFAULT 0,
  reason text,
  e_invoice_irn text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_billing_credit_debit_note_parent ON billing.credit_debit_note(parent_invoice_id);

-- 8. Payment Advice (billing.payment_advice)
CREATE TABLE IF NOT EXISTS billing.payment_advice (
  invoice_id uuid PRIMARY KEY REFERENCES billing.invoice(id) ON DELETE CASCADE,
  pa_received_date date,
  pa_file_url text,
  penalty_deduction_amount numeric(18,2) DEFAULT 0,
  deduction_remarks text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- updated_at triggers
CREATE OR REPLACE FUNCTION billing.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS billing_po_wo_updated_at ON billing.po_wo;
CREATE TRIGGER billing_po_wo_updated_at
  BEFORE UPDATE ON billing.po_wo
  FOR EACH ROW EXECUTE FUNCTION billing.set_updated_at();

DROP TRIGGER IF EXISTS billing_invoice_updated_at ON billing.invoice;
CREATE TRIGGER billing_invoice_updated_at
  BEFORE UPDATE ON billing.invoice
  FOR EACH ROW EXECUTE FUNCTION billing.set_updated_at();

DROP TRIGGER IF EXISTS billing_payment_advice_updated_at ON billing.payment_advice;
CREATE TRIGGER billing_payment_advice_updated_at
  BEFORE UPDATE ON billing.payment_advice
  FOR EACH ROW EXECUTE FUNCTION billing.set_updated_at();

-- ROW LEVEL SECURITY
ALTER TABLE billing.po_wo ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing.po_rate_category ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing.po_contact_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing.invoice ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing.invoice_line_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing.invoice_attachment ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing.credit_debit_note ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing.payment_advice ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "billing_access_po_wo" ON billing.po_wo;
CREATE POLICY "billing_access_po_wo"
  ON billing.po_wo FOR ALL TO authenticated
  USING (billing.current_user_has_billing_access())
  WITH CHECK (billing.current_user_has_billing_access());

DROP POLICY IF EXISTS "billing_access_po_rate_category" ON billing.po_rate_category;
CREATE POLICY "billing_access_po_rate_category"
  ON billing.po_rate_category FOR ALL TO authenticated
  USING (billing.current_user_has_billing_access())
  WITH CHECK (billing.current_user_has_billing_access());

DROP POLICY IF EXISTS "billing_access_po_contact_log" ON billing.po_contact_log;
CREATE POLICY "billing_access_po_contact_log"
  ON billing.po_contact_log FOR ALL TO authenticated
  USING (billing.current_user_has_billing_access())
  WITH CHECK (billing.current_user_has_billing_access());

DROP POLICY IF EXISTS "billing_access_invoice" ON billing.invoice;
CREATE POLICY "billing_access_invoice"
  ON billing.invoice FOR ALL TO authenticated
  USING (billing.current_user_has_billing_access())
  WITH CHECK (billing.current_user_has_billing_access());

DROP POLICY IF EXISTS "billing_access_invoice_line_item" ON billing.invoice_line_item;
CREATE POLICY "billing_access_invoice_line_item"
  ON billing.invoice_line_item FOR ALL TO authenticated
  USING (billing.current_user_has_billing_access())
  WITH CHECK (billing.current_user_has_billing_access());

CREATE POLICY "billing_access_invoice_attachment"
  ON billing.invoice_attachment FOR ALL TO authenticated
  USING (billing.current_user_has_billing_access())
  WITH CHECK (billing.current_user_has_billing_access());

DROP POLICY IF EXISTS "billing_access_credit_debit_note" ON billing.credit_debit_note;
CREATE POLICY "billing_access_credit_debit_note"
  ON billing.credit_debit_note FOR ALL TO authenticated
  USING (billing.current_user_has_billing_access())
  WITH CHECK (billing.current_user_has_billing_access());

DROP POLICY IF EXISTS "billing_access_payment_advice" ON billing.payment_advice;
CREATE POLICY "billing_access_payment_advice"
  ON billing.payment_advice FOR ALL TO authenticated
  USING (billing.current_user_has_billing_access())
  WITH CHECK (billing.current_user_has_billing_access());

-- Grants so authenticated role can use billing schema (RLS still applies)
GRANT USAGE ON SCHEMA billing TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA billing TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA billing TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA billing GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated;

-- =============================================================================
-- BEGIN: 20260210120000_admin_employee_master_extended_columns.sql
-- =============================================================================
ALTER TABLE public.admin_ifsp_employee_master
  ADD COLUMN IF NOT EXISTS location text,
  ADD COLUMN IF NOT EXISTS uan_no text,
  ADD COLUMN IF NOT EXISTS esic_no text,
  ADD COLUMN IF NOT EXISTS bank_name text,
  ADD COLUMN IF NOT EXISTS bank_account_no text,
  ADD COLUMN IF NOT EXISTS ifsc_code text,
  ADD COLUMN IF NOT EXISTS email_id text,
  ADD COLUMN IF NOT EXISTS marital_status text;

COMMENT ON COLUMN public.admin_ifsp_employee_master.employee_id IS 'IFSPL_employee_system_id - sequential per tenant; app-generated.';
COMMENT ON COLUMN public.admin_ifsp_employee_master.other_experience IS 'Previous_Experience (years before IFSPL).';
COMMENT ON COLUMN public.admin_ifsp_employee_master.years_of_experience IS 'Optional snapshot; UI shows Total = Previous + tenure from Date_of_Joining.';

-- =============================================================================
-- BEGIN: 20260401123000_add_qty_to_po_rate_category.sql
-- =============================================================================
ALTER TABLE billing.po_rate_category
ADD COLUMN IF NOT EXISTS qty numeric(18,2) NOT NULL DEFAULT 0;

-- =============================================================================
-- BEGIN: 20260401130000_add_remarks_to_po_wo.sql
-- =============================================================================
ALTER TABLE billing.po_wo
ADD COLUMN IF NOT EXISTS remarks text;

UPDATE billing.po_wo
SET remarks = payment_terms
WHERE remarks IS NULL AND payment_terms IS NOT NULL;

-- =============================================================================
-- BEGIN: 20260401134500_dedupe_po_rate_category_and_add_unique_index.sql
-- =============================================================================
DELETE FROM billing.po_rate_category a
USING billing.po_rate_category b
WHERE a.po_id = b.po_id
  AND COALESCE(a.sort_order, 0) = COALESCE(b.sort_order, 0)
  AND a.id > b.id;

CREATE UNIQUE INDEX IF NOT EXISTS uq_billing_po_rate_category_po_sort
  ON billing.po_rate_category(po_id, sort_order);

-- =============================================================================
-- BEGIN: 20260402120000_billing_po_wo_realtime.sql
-- =============================================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'billing'
      AND tablename = 'po_wo'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE billing.po_wo;
  END IF;
END $$;

-- =============================================================================
-- BEGIN: 20260402180000_billing_invoice_po_enhancements.sql
-- =============================================================================
ALTER TABLE billing.invoice
  ADD COLUMN IF NOT EXISTS bill_number text,
  ADD COLUMN IF NOT EXISTS billing_month text,
  ADD COLUMN IF NOT EXISTS seller_cin text,
  ADD COLUMN IF NOT EXISTS seller_pan text,
  ADD COLUMN IF NOT EXISTS msme_registration_no text,
  ADD COLUMN IF NOT EXISTS msme_clause text,
  ADD COLUMN IF NOT EXISTS billing_duration_from date,
  ADD COLUMN IF NOT EXISTS billing_duration_to date,
  ADD COLUMN IF NOT EXISTS invoice_header_remarks text,
  ADD COLUMN IF NOT EXISTS terms_template_key text,
  ADD COLUMN IF NOT EXISTS invoice_kind text DEFAULT 'tax',
  ADD COLUMN IF NOT EXISTS gst_supply_type text DEFAULT 'intra',
  ADD COLUMN IF NOT EXISTS igst_rate numeric(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS igst_amt numeric(18,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS digital_signature_data_url text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'billing_invoice_kind_check'
  ) THEN
    ALTER TABLE billing.invoice
      ADD CONSTRAINT billing_invoice_kind_check
      CHECK (invoice_kind IS NULL OR invoice_kind IN ('tax', 'proforma', 'draft'));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'billing_invoice_gst_supply_check'
  ) THEN
    ALTER TABLE billing.invoice
      ADD CONSTRAINT billing_invoice_gst_supply_check
      CHECK (gst_supply_type IS NULL OR gst_supply_type IN ('intra', 'inter', 'sez_zero'));
  END IF;
END $$;

ALTER TABLE billing.invoice_line_item
  ADD COLUMN IF NOT EXISTS po_qty numeric(18,2),
  ADD COLUMN IF NOT EXISTS actual_duty numeric(18,2),
  ADD COLUMN IF NOT EXISTS authorized_duty numeric(18,2);

ALTER TABLE billing.po_wo
  ADD COLUMN IF NOT EXISTS vendor_code text,
  ADD COLUMN IF NOT EXISTS gst_supply_type text DEFAULT 'intra',
  ADD COLUMN IF NOT EXISTS update_history jsonb DEFAULT '[]'::jsonb;

COMMENT ON COLUMN billing.invoice.invoice_kind IS 'tax | proforma | draft - PDF header only; same layout.';
COMMENT ON COLUMN billing.po_wo.update_history IS 'JSON array of {at, summary} for PO change log.';

-- =============================================================================
-- BEGIN: 20260406120000_po_invoice_terms_shipping_seller.sql
-- =============================================================================
ALTER TABLE billing.po_wo
  ADD COLUMN IF NOT EXISTS shipping_address text,
  ADD COLUMN IF NOT EXISTS invoice_terms_text text,
  ADD COLUMN IF NOT EXISTS seller_cin text,
  ADD COLUMN IF NOT EXISTS seller_pan text,
  ADD COLUMN IF NOT EXISTS msme_registration_no text,
  ADD COLUMN IF NOT EXISTS msme_clause text,
  ADD COLUMN IF NOT EXISTS place_of_supply text;

ALTER TABLE billing.invoice
  ADD COLUMN IF NOT EXISTS client_shipping_address text,
  ADD COLUMN IF NOT EXISTS terms_custom_text text,
  ADD COLUMN IF NOT EXISTS place_of_supply text;

COMMENT ON COLUMN billing.po_wo.invoice_terms_text IS 'Terms printed on tax invoice; maintained in PO Entry only.';
COMMENT ON COLUMN billing.po_wo.shipping_address IS 'Consignee (ship-to); if null/empty, billing_address is used on invoice.';
COMMENT ON COLUMN billing.invoice.client_shipping_address IS 'Snapshot of ship-to at invoice save.';
COMMENT ON COLUMN billing.invoice.terms_custom_text IS 'Snapshot of PO invoice_terms_text (or override) at invoice save.';

-- =============================================================================
-- BEGIN: 20260406140000_invoice_line_qty_three_decimals.sql
-- =============================================================================
ALTER TABLE billing.invoice_line_item
  ALTER COLUMN quantity TYPE numeric(18,3);

-- =============================================================================
-- BEGIN: 20260406170000_employee_master_import_columns.sql
-- =============================================================================
ALTER TABLE public.admin_ifsp_employee_master
  ADD COLUMN IF NOT EXISTS emp_code text,
  ADD COLUMN IF NOT EXISTS timestamp text,
  ADD COLUMN IF NOT EXISTS son_details text,
  ADD COLUMN IF NOT EXISTS daughter_details text,
  ADD COLUMN IF NOT EXISTS educational_qualification text;

-- =============================================================================
-- BEGIN: 20260409120000_billing_po_supplementary_bills.sql
-- =============================================================================
ALTER TABLE billing.po_wo
  ADD COLUMN IF NOT EXISTS is_supplementary boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS supplementary_parent_po_id uuid,
  ADD COLUMN IF NOT EXISTS supplementary_request_status text,
  ADD COLUMN IF NOT EXISTS supplementary_reason text,
  ADD COLUMN IF NOT EXISTS supplementary_requested_at timestamptz,
  ADD COLUMN IF NOT EXISTS supplementary_approved_at timestamptz;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'billing_po_wo_supplementary_request_status_check'
  ) THEN
    ALTER TABLE billing.po_wo
      ADD CONSTRAINT billing_po_wo_supplementary_request_status_check
      CHECK (
        supplementary_request_status IS NULL
        OR supplementary_request_status IN ('pending', 'approved', 'rejected')
      );
  END IF;
END $$;

COMMENT ON COLUMN billing.po_wo.is_supplementary IS 'True when this PO/WO row is a supplementary-billing mock PO created by app.';
COMMENT ON COLUMN billing.po_wo.supplementary_parent_po_id IS 'Parent PO/WO id that this supplementary row derives from.';
COMMENT ON COLUMN billing.po_wo.supplementary_request_status IS 'pending | approved | rejected for supplementary billing request on the parent PO.';

-- =============================================================================
-- BEGIN: 20260409130000_billing_po_renewed_po_number_and_contract.sql
-- =============================================================================
ALTER TABLE billing.po_wo
  ADD COLUMN IF NOT EXISTS renewed_po_wo_number text,
  ADD COLUMN IF NOT EXISTS renewed_total_contract_value numeric(18,2),
  ADD COLUMN IF NOT EXISTS renewed_start_date date,
  ADD COLUMN IF NOT EXISTS renewed_end_date date;

COMMENT ON COLUMN billing.po_wo.renewed_po_wo_number IS 'Second/renewed PO/WO number after contract renewal (entered in app).';
COMMENT ON COLUMN billing.po_wo.renewed_total_contract_value IS 'Second/renewed total contract value after renewal (entered in app).';
COMMENT ON COLUMN billing.po_wo.renewed_start_date IS 'Renewal period start date (for renewed PO/WO).';
COMMENT ON COLUMN billing.po_wo.renewed_end_date IS 'Renewal period end date (for renewed PO/WO).';

-- =============================================================================
-- BEGIN: 20260409140000_billing_po_renewal_cycles.sql
-- =============================================================================
ALTER TABLE billing.po_wo
  ADD COLUMN IF NOT EXISTS renewal_cycles jsonb DEFAULT '[]'::jsonb;

COMMENT ON COLUMN billing.po_wo.renewal_cycles IS 'Array of renewal cycles: [{po_wo_number,total_contract_value,start_date,end_date,approved_at}]';

-- =============================================================================
-- BEGIN: 20260410130000_po_billing_logic_line_penalty.sql
-- =============================================================================
ALTER TABLE billing.po_wo
  ADD COLUMN IF NOT EXISTS monthly_duty_qty_mode text,
  ADD COLUMN IF NOT EXISTS lump_sum_billing_mode text;

COMMENT ON COLUMN billing.po_wo.monthly_duty_qty_mode IS 'Monthly: po_geometry = (actual/auth)*PO qty; duty_ratio = actual/auth as qty.';
COMMENT ON COLUMN billing.po_wo.lump_sum_billing_mode IS 'Lump Sum: normal | penalty (line penalty column) | fire_tender (extra Fire Tender row).';

ALTER TABLE billing.invoice_line_item
  ADD COLUMN IF NOT EXISTS line_penalty numeric(18,2) DEFAULT 0;

-- =============================================================================
-- BEGIN: 20260410150000_invoice_post_contract_buffer.sql
-- =============================================================================
ALTER TABLE billing.invoice
  ADD COLUMN IF NOT EXISTS is_post_contract_buffer boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN billing.invoice.is_post_contract_buffer IS 'True: invoice was raised while post-contract billing was approved; PO/WO header may be updated when renewal is approved.';

-- =============================================================================
-- BEGIN: 20260411120000_lump_sum_category_penalty_truck_lines.sql
-- =============================================================================
ALTER TABLE billing.po_rate_category
  ADD COLUMN IF NOT EXISTS category_penalty numeric(18,2) DEFAULT 0;

ALTER TABLE billing.invoice_line_item
  ADD COLUMN IF NOT EXISTS po_reference_rate numeric(18,2),
  ADD COLUMN IF NOT EXISTS is_truck_line boolean DEFAULT false;

UPDATE billing.po_wo SET lump_sum_billing_mode = 'truck' WHERE lump_sum_billing_mode = 'fire_tender';

COMMENT ON COLUMN billing.po_rate_category.category_penalty IS 'Lump sum penalty mode: subtract from duty-adjusted rate on invoice.';
COMMENT ON COLUMN billing.invoice_line_item.po_reference_rate IS 'Snapshot of PO category rate for lump-sum duty lines.';
COMMENT ON COLUMN billing.invoice_line_item.is_truck_line IS 'True: invoice line uses manual QtyxRate only (truck add-on rows).';

-- =============================================================================
-- BEGIN: 20260412110000_add_on_invoices.sql
-- =============================================================================
ALTER TABLE billing.invoice
  ADD COLUMN IF NOT EXISTS is_add_on boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS add_on_type text;

CREATE TABLE IF NOT EXISTS billing.add_on_invoice (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL REFERENCES billing.invoice(id) ON DELETE CASCADE,
  po_id uuid REFERENCES billing.po_wo(id) ON DELETE SET NULL,
  oc_number text,
  client_name text,
  location_name text,
  add_on_type text NOT NULL,
  remarks text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_billing_add_on_invoice_invoice_id ON billing.add_on_invoice(invoice_id);
CREATE INDEX IF NOT EXISTS idx_billing_add_on_invoice_oc_number ON billing.add_on_invoice(oc_number);

ALTER TABLE billing.add_on_invoice ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "billing_access_add_on_invoice" ON billing.add_on_invoice;
CREATE POLICY "billing_access_add_on_invoice"
  ON billing.add_on_invoice FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role IN ('admin', 'billing')
    )
    OR NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid())
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role IN ('admin', 'billing')
    )
    OR NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid())
  );

-- =============================================================================
-- BEGIN: 20260413120000_invoice_cn_dn_request_note_snapshot.sql
-- =============================================================================
ALTER TABLE billing.invoice
  ADD COLUMN IF NOT EXISTS cn_dn_request_status text,
  ADD COLUMN IF NOT EXISTS cn_dn_request_note_type text,
  ADD COLUMN IF NOT EXISTS cn_dn_request_reason text,
  ADD COLUMN IF NOT EXISTS cn_dn_requested_at timestamptz,
  ADD COLUMN IF NOT EXISTS cn_dn_approved_at timestamptz;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'billing_invoice_cn_dn_request_status_check'
  ) THEN
    ALTER TABLE billing.invoice
      ADD CONSTRAINT billing_invoice_cn_dn_request_status_check
      CHECK (
        cn_dn_request_status IS NULL
        OR cn_dn_request_status IN ('pending', 'approved', 'rejected')
      );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'billing_invoice_cn_dn_request_note_type_check'
  ) THEN
    ALTER TABLE billing.invoice
      ADD CONSTRAINT billing_invoice_cn_dn_request_note_type_check
      CHECK (
        cn_dn_request_note_type IS NULL
        OR cn_dn_request_note_type IN ('credit', 'debit')
      );
  END IF;
END $$;

COMMENT ON COLUMN billing.invoice.cn_dn_request_status IS 'pending | approved | rejected - Commercial approval to raise CN/DN against this tax invoice.';
COMMENT ON COLUMN billing.invoice.cn_dn_request_note_type IS 'credit | debit - requested note type while pending/approved.';

ALTER TABLE billing.credit_debit_note
  ADD COLUMN IF NOT EXISTS note_tax_invoice_number text,
  ADD COLUMN IF NOT EXISTS invoice_snapshot jsonb;

COMMENT ON COLUMN billing.credit_debit_note.note_tax_invoice_number IS 'Display document no., e.g. CN-{parent tax invoice no.} or DN-{...}.';
COMMENT ON COLUMN billing.credit_debit_note.invoice_snapshot IS 'Full payload for tax-invoice-layout PDF/HTML (items, GST, buyer, etc.).';

-- =============================================================================
-- BEGIN: 20260413150000_fix_profiles_rls_recursion.sql
-- =============================================================================
CREATE OR REPLACE FUNCTION public.is_current_user_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND role in ('super_admin', 'super_admin_pro')
  );
$$;

DROP POLICY IF EXISTS "Admins can read all profiles" ON public.profiles;
DROP POLICY IF EXISTS "Admins can update any profile" ON public.profiles;

CREATE POLICY "Admins can read all profiles"
  ON public.profiles FOR SELECT
  USING (public.is_current_user_admin());

CREATE POLICY "Admins can update any profile"
  ON public.profiles FOR UPDATE
  USING (public.is_current_user_admin());

-- =============================================================================
-- BEGIN: 20260414120000_manpower_enquiries_and_storage.sql
-- =============================================================================
create table if not exists public.manpower_enquiries (
  id uuid primary key default gen_random_uuid(),
  client text not null default '',
  phone text,
  email text,
  street text,
  street2 text,
  city text,
  state text,
  zip text,
  country text,
  priority integer not null default 1,
  source text,
  due_date date,
  rfq_available boolean not null default false,
  project_estimation text,
  duration jsonb not null default '{"days": 0, "months": 0, "years": 0}'::jsonb,
  documents text,
  manpower_required text,
  fire_tender_required boolean not null default false,
  contacts jsonb not null default '[]'::jsonb,
  handled_by text,
  authorization_to text,
  enquiry_number text,
  status text not null default 'Pending',
  user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists manpower_enquiries_enquiry_number_unique
  on public.manpower_enquiries (enquiry_number)
  where enquiry_number is not null;

create index if not exists manpower_enquiries_created_at_idx
  on public.manpower_enquiries (created_at desc);

alter table public.manpower_enquiries enable row level security;

drop policy if exists "manpower_enquiries_select_authenticated" on public.manpower_enquiries;
drop policy if exists "manpower_enquiries_insert_authenticated" on public.manpower_enquiries;
drop policy if exists "manpower_enquiries_update_authenticated" on public.manpower_enquiries;
drop policy if exists "manpower_enquiries_delete_authenticated" on public.manpower_enquiries;

create policy "manpower_enquiries_select_authenticated"
  on public.manpower_enquiries for select
  to authenticated
  using (true);

create policy "manpower_enquiries_insert_authenticated"
  on public.manpower_enquiries for insert
  to authenticated
  with check (true);

create policy "manpower_enquiries_update_authenticated"
  on public.manpower_enquiries for update
  to authenticated
  using (true)
  with check (true);

create policy "manpower_enquiries_delete_authenticated"
  on public.manpower_enquiries for delete
  to authenticated
  using (true);

drop trigger if exists manpower_enquiries_updated_at on public.manpower_enquiries;
create trigger manpower_enquiries_updated_at
  before update on public.manpower_enquiries
  for each row execute function public.set_updated_at();

insert into storage.buckets (id, name, public)
values ('manpower-docs', 'manpower-docs', false)
on conflict (id) do nothing;

drop policy if exists "manpower_docs_insert_authenticated" on storage.objects;
drop policy if exists "manpower_docs_select_authenticated" on storage.objects;
drop policy if exists "manpower_docs_update_authenticated" on storage.objects;
drop policy if exists "manpower_docs_delete_authenticated" on storage.objects;

create policy "manpower_docs_insert_authenticated"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'manpower-docs');

create policy "manpower_docs_select_authenticated"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'manpower-docs');

create policy "manpower_docs_update_authenticated"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'manpower-docs');

create policy "manpower_docs_delete_authenticated"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'manpower-docs');

-- =============================================================================
-- BEGIN: root/database_schema_marketing_site_visits.sql
-- =============================================================================
-- SQL Script for marketing_site_visits table
-- This script will add missing columns if the table already exists
-- Or create the table if it doesn't exist

CREATE TABLE IF NOT EXISTS marketing_site_visits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  executive_names TEXT,
  visitor_name TEXT,
  company_name TEXT,
  client_name TEXT,
  designation TEXT,
  site_location TEXT,
  mobile_number TEXT,
  email_id TEXT,
  product_interest TEXT,
  discussion_note TEXT,
  visit_date DATE,
  purpose_of_visit TEXT,
  travel_expenses DECIMAL(10,2) DEFAULT 0,
  food_expenses DECIMAL(10,2) DEFAULT 0,
  accommodation DECIMAL(10,2) DEFAULT 0,
  other_expenses DECIMAL(10,2) DEFAULT 0,
  total_expense DECIMAL(10,2) DEFAULT 0,
  approved_amount DECIMAL(10,2),
  status TEXT DEFAULT 'Pending Paid',
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_by UUID REFERENCES auth.users(id),
  updated_at TIMESTAMP DEFAULT NOW()
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'executive_names') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN executive_names TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'visitor_name') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN visitor_name TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'company_name') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN company_name TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'client_name') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN client_name TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'designation') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN designation TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'site_location') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN site_location TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'mobile_number') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN mobile_number TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'email_id') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN email_id TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'product_interest') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN product_interest TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'discussion_note') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN discussion_note TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'visit_date') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN visit_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'purpose_of_visit') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN purpose_of_visit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'travel_expenses') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN travel_expenses DECIMAL(10,2) DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'food_expenses') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN food_expenses DECIMAL(10,2) DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'accommodation') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN accommodation DECIMAL(10,2) DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'other_expenses') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN other_expenses DECIMAL(10,2) DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'total_expense') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN total_expense DECIMAL(10,2) DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'approved_amount') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN approved_amount DECIMAL(10,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'status') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN status TEXT DEFAULT 'Pending Paid';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'created_by') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN created_by UUID REFERENCES auth.users(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'created_at') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'updated_by') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN updated_by UUID REFERENCES auth.users(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_site_visits' AND column_name = 'updated_at') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_marketing_site_visits_visit_date ON marketing_site_visits(visit_date);
CREATE INDEX IF NOT EXISTS idx_marketing_site_visits_status ON marketing_site_visits(status);
CREATE INDEX IF NOT EXISTS idx_marketing_site_visits_client_name ON marketing_site_visits(client_name);

-- =============================================================================
-- BEGIN: root/marketing_quotation_revisions_schema_update.sql
-- =============================================================================
CREATE TABLE IF NOT EXISTS marketing_quotation_revisions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    quotation_id UUID REFERENCES marketing_quotations(id) ON DELETE CASCADE,
    revision_number INTEGER NOT NULL,
    revision_date DATE NOT NULL DEFAULT CURRENT_DATE,
    remarks TEXT,
    changes_summary TEXT,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),
    updated_by UUID REFERENCES auth.users(id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'marketing_quotations'
        AND column_name = 'follow_up_date'
    ) THEN
        ALTER TABLE marketing_quotations
        ADD COLUMN follow_up_date DATE;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS marketing_notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT,
    quotation_id UUID REFERENCES marketing_quotations(id) ON DELETE CASCADE,
    enquiry_id UUID REFERENCES marketing_enquiries(id) ON DELETE CASCADE,
    follow_up_id UUID REFERENCES marketing_follow_ups(id) ON DELETE CASCADE,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id)
);

CREATE INDEX IF NOT EXISTS idx_quotation_revisions_quotation_id ON marketing_quotation_revisions(quotation_id);
CREATE INDEX IF NOT EXISTS idx_quotation_revisions_date ON marketing_quotation_revisions(revision_date);
CREATE INDEX IF NOT EXISTS idx_quotation_revisions_number ON marketing_quotation_revisions(quotation_id, revision_number);
CREATE INDEX IF NOT EXISTS idx_quotation_revisions_status ON marketing_quotation_revisions(status);
CREATE INDEX IF NOT EXISTS idx_quotations_follow_up_date ON marketing_quotations(follow_up_date);
CREATE INDEX IF NOT EXISTS idx_notifications_type ON marketing_notifications(type);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON marketing_notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON marketing_notifications(created_at);

ALTER TABLE marketing_quotation_revisions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view all quotation revisions" ON marketing_quotation_revisions;
CREATE POLICY "Users can view all quotation revisions" ON marketing_quotation_revisions FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can insert quotation revisions" ON marketing_quotation_revisions;
CREATE POLICY "Users can insert quotation revisions" ON marketing_quotation_revisions FOR INSERT WITH CHECK (auth.uid() = created_by);
DROP POLICY IF EXISTS "Users can update quotation revisions" ON marketing_quotation_revisions;
CREATE POLICY "Users can update quotation revisions" ON marketing_quotation_revisions FOR UPDATE USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Users can delete quotation revisions" ON marketing_quotation_revisions;
CREATE POLICY "Users can delete quotation revisions" ON marketing_quotation_revisions FOR DELETE USING (true);

ALTER TABLE marketing_notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view their notifications" ON marketing_notifications;
CREATE POLICY "Users can view their notifications" ON marketing_notifications FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can insert notifications" ON marketing_notifications;
CREATE POLICY "Users can insert notifications" ON marketing_notifications FOR INSERT WITH CHECK (auth.uid() = created_by);
DROP POLICY IF EXISTS "Users can update notifications" ON marketing_notifications;
CREATE POLICY "Users can update notifications" ON marketing_notifications FOR UPDATE USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Users can delete notifications" ON marketing_notifications;
CREATE POLICY "Users can delete notifications" ON marketing_notifications FOR DELETE USING (true);

CREATE OR REPLACE FUNCTION update_follow_up_status()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.follow_up_date < CURRENT_DATE AND NEW.status = 'Pending' THEN
        NEW.status := 'Overdue';
    END IF;
    IF NEW.status = 'Completed' AND NEW.follow_up_date < CURRENT_DATE THEN
        RETURN NEW;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_follow_up_status ON marketing_follow_ups;
CREATE TRIGGER trigger_update_follow_up_status
    BEFORE INSERT OR UPDATE ON marketing_follow_ups
    FOR EACH ROW EXECUTE FUNCTION update_follow_up_status();

CREATE OR REPLACE FUNCTION update_revision_status()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.revision_date < CURRENT_DATE AND NEW.status = 'Pending' THEN
        NEW.status := 'Overdue';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_revision_status ON marketing_quotation_revisions;
CREATE TRIGGER trigger_update_revision_status
    BEFORE INSERT OR UPDATE ON marketing_quotation_revisions
    FOR EACH ROW EXECUTE FUNCTION update_revision_status();

CREATE OR REPLACE VIEW marketing_revision_summary AS
SELECT
    qr.id,
    qr.quotation_id,
    q.quotation_number,
    qr.revision_number,
    qr.revision_date,
    qr.remarks,
    qr.status,
    qr.created_at,
    c.client_name,
    c.contact_email,
    CASE
        WHEN qr.revision_date = CURRENT_DATE THEN 'Due Today'
        WHEN qr.revision_date < CURRENT_DATE AND qr.status = 'Pending' THEN 'Overdue'
        WHEN qr.status = 'Completed' THEN 'Completed'
        ELSE 'Upcoming'
    END AS computed_status
FROM marketing_quotation_revisions qr
JOIN marketing_quotations q ON qr.quotation_id = q.id
LEFT JOIN marketing_clients c ON q.client_id = c.id;

-- =============================================================================
-- BEGIN: root/marketing_enquiry_documents_schema.sql
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.marketing_enquiry_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  enquiry_id UUID NOT NULL REFERENCES public.marketing_enquiries(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_type TEXT,
  file_size BIGINT,
  uploaded_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'marketing_enquiry_documents'
      AND column_name = 'created_at'
  ) THEN
    ALTER TABLE public.marketing_enquiry_documents
      ADD COLUMN created_at TIMESTAMPTZ DEFAULT NOW();
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_marketing_enquiry_documents_enquiry_id
  ON public.marketing_enquiry_documents(enquiry_id);

ALTER TABLE public.marketing_enquiry_documents ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow read marketing_enquiry_documents" ON public.marketing_enquiry_documents;
CREATE POLICY "Allow read marketing_enquiry_documents" ON public.marketing_enquiry_documents FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "Allow insert marketing_enquiry_documents" ON public.marketing_enquiry_documents;
CREATE POLICY "Allow insert marketing_enquiry_documents" ON public.marketing_enquiry_documents FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Allow delete marketing_enquiry_documents" ON public.marketing_enquiry_documents;
CREATE POLICY "Allow delete marketing_enquiry_documents" ON public.marketing_enquiry_documents FOR DELETE TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow authenticated upload marketing-documents" ON storage.objects;
CREATE POLICY "Allow authenticated upload marketing-documents"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'marketing-documents');
DROP POLICY IF EXISTS "Allow authenticated read marketing-documents" ON storage.objects;
CREATE POLICY "Allow authenticated read marketing-documents"
  ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'marketing-documents');
DROP POLICY IF EXISTS "Allow authenticated delete marketing-documents" ON storage.objects;
CREATE POLICY "Allow authenticated delete marketing-documents"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'marketing-documents');

-- =============================================================================
-- BEGIN: root/add_assigned_to_name_marketing_enquiries.sql
-- =============================================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'marketing_enquiries' AND column_name = 'assigned_to_name'
  ) THEN
    ALTER TABLE public.marketing_enquiries ADD COLUMN assigned_to_name TEXT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'marketing_enquiries' AND column_name = 'assigned_to_ids'
  ) THEN
    ALTER TABLE public.marketing_enquiries ADD COLUMN assigned_to_ids JSONB DEFAULT '[]'::jsonb;
    COMMENT ON COLUMN public.marketing_enquiries.assigned_to_ids IS 'Array of user IDs (from profiles) assigned to this enquiry.';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'marketing_enquiries' AND column_name = 'assigned_to_custom_names'
  ) THEN
    ALTER TABLE public.marketing_enquiries ADD COLUMN assigned_to_custom_names JSONB DEFAULT '[]'::jsonb;
    COMMENT ON COLUMN public.marketing_enquiries.assigned_to_custom_names IS 'Array of custom assignee names (not system users).';
  END IF;
END $$;

UPDATE public.marketing_enquiries
SET
  assigned_to_ids = CASE
    WHEN assigned_to IS NOT NULL AND (assigned_to_ids IS NULL OR assigned_to_ids = '[]'::jsonb)
    THEN jsonb_build_array(assigned_to::text)
    ELSE COALESCE(assigned_to_ids, '[]'::jsonb)
  END,
  assigned_to_custom_names = CASE
    WHEN assigned_to_name IS NOT NULL AND assigned_to_name <> '' AND (assigned_to_custom_names IS NULL OR assigned_to_custom_names = '[]'::jsonb)
    THEN jsonb_build_array(assigned_to_name)
    ELSE COALESCE(assigned_to_custom_names, '[]'::jsonb)
  END
WHERE assigned_to IS NOT NULL OR (assigned_to_name IS NOT NULL AND assigned_to_name <> '');

-- =============================================================================
-- END: Consolidated migrations
-- =============================================================================
-- =============================================================================
-- BEGIN: root/marketing_quotation_revisions_schema.sql
-- =============================================================================
CREATE TABLE IF NOT EXISTS marketing_quotation_revisions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    quotation_id UUID REFERENCES marketing_quotations(id) ON DELETE CASCADE,
    revision_number INTEGER NOT NULL,
    revision_date DATE NOT NULL DEFAULT CURRENT_DATE,
    remarks TEXT,
    changes_summary TEXT,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),
    updated_by UUID REFERENCES auth.users(id)
);

-- =============================================================================
-- BEGIN: root/ifsp_employee_master_updated_schema.sql
-- =============================================================================
CREATE TABLE IF NOT EXISTS ifsp_employee_history (
    id bigint generated by default as identity primary key,
    employee_id bigint not null references ifsp_employees(id) on delete cascade,
    field_name text not null,
    old_value text,
    new_value text,
    changed_by text not null,
    changed_at timestamptz default now(),
    change_reason text,
    user_id uuid references auth.users(id)
);
ALTER TABLE ifsp_employee_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own employee history" ON ifsp_employee_history FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own employee history" ON ifsp_employee_history FOR INSERT WITH CHECK (auth.uid() = user_id);

-- =============================================================================
-- BEGIN: root/missing_tables.sql
-- =============================================================================
CREATE TABLE IF NOT EXISTS accessories (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);
CREATE TABLE IF NOT EXISTS costing_accessories (
    id bigint generated by default as identity primary key,
    tender_id bigint not null references tenders(id) on delete cascade,
    accessory_id bigint not null references accessories(id) on delete cascade,
    qty numeric default 0,
    price numeric default 0,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS unique_accessory_per_tender ON costing_accessories(tender_id, accessory_id);

-- =============================================================================
-- BEGIN: root/vehicle_management_schema.sql
-- =============================================================================
CREATE TABLE IF NOT EXISTS drivers (
    id bigint generated by default as identity primary key,
    employee_id text unique,
    full_name text not null,
    contact_number text,
    email text,
    license_number text,
    license_type text,
    license_expiry_date date,
    department text,
    designation text,
    is_active boolean default true,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);
CREATE TABLE IF NOT EXISTS vehicles_master (
    id bigint generated by default as identity primary key,
    vehicle_type text not null,
    registration_number text not null unique,
    make text not null,
    model text not null,
    assigned_driver_id uuid references auth.users(id),
    vehicle_status text not null default 'Available',
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);
CREATE TABLE IF NOT EXISTS vehicle_documents (
    id bigint generated by default as identity primary key,
    vehicle_id bigint not null references vehicles_master(id) on delete cascade,
    document_type text not null,
    document_number text,
    issue_date date,
    expiry_date date not null,
    provider text,
    premium_amount numeric,
    file_url text,
    alert_status text default 'Active',
    remarks text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);

-- =============================================================================
-- BEGIN: root/vehicle_management_sample_data.sql
-- =============================================================================
INSERT INTO drivers (employee_id, full_name, contact_number, email, license_number, license_type, license_expiry_date, department, designation, is_active, user_id) VALUES
('EMP001', 'Rajesh Kumar', '9876543210', 'rajesh.kumar@indus.com', 'DL123456789', 'LMV (Light Motor Vehicle)', '2025-12-31', 'Transport', 'Senior Driver', true, auth.uid());

INSERT INTO vehicles_master (vehicle_type, registration_number, make, model, assigned_driver_id, vehicle_status, user_id) VALUES
('Fire Tender', 'MH01AB1234', 'Tata', 'Fire Tender Model X', auth.uid(), 'Available', auth.uid());

-- =============================================================================
-- END: Consolidated migrations
-- =============================================================================
-- =============================================================================
-- BEGIN: root/ifsp_employee_master_sample_data.sql
-- =============================================================================
INSERT INTO ifsp_employees (
    employee_id, first_name, last_name, email, phone, date_of_birth, date_of_joining,
    department, designation, reporting_manager, employment_type, status, basic_salary,
    address, emergency_contact_name, emergency_contact_phone, emergency_contact_relation,
    qualifications, skills, previous_experience, notes, user_id
) VALUES
('EMP001', 'Rajesh', 'Kumar', 'rajesh.kumar@ifsp.com', '9876543210', '1985-03-15', '2020-01-15',
 'HR', 'Manager', 'CEO', 'Full Time', 'Active', 75000,
 '123 Main Street, Mumbai', 'Sita Kumar', '9876543211', 'Wife',
 'MBA in HR, B.Com', 'Leadership, Communication, HR Management', 8.5,
 'Experienced HR professional with strong leadership skills', auth.uid());

-- =============================================================================
-- BEGIN: root/marketing_site_visits_schema.sql
-- =============================================================================
CREATE TABLE IF NOT EXISTS marketing_site_visits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    executive_names TEXT NOT NULL,
    client_name TEXT NOT NULL,
    site_location TEXT NOT NULL,
    visit_date DATE NOT NULL,
    purpose_of_visit TEXT,
    travel_expenses DECIMAL(12, 2) DEFAULT 0,
    food_expenses DECIMAL(12, 2) DEFAULT 0,
    accommodation DECIMAL(12, 2) DEFAULT 0,
    other_expenses DECIMAL(12, 2) DEFAULT 0,
    total_expense DECIMAL(12, 2) DEFAULT 0,
    approved_amount DECIMAL(12, 2),
    status TEXT DEFAULT 'Pending Paid',
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),
    updated_by UUID REFERENCES auth.users(id)
);
CREATE INDEX IF NOT EXISTS idx_site_visits_date ON marketing_site_visits(visit_date);
CREATE INDEX IF NOT EXISTS idx_site_visits_client ON marketing_site_visits(client_name);
CREATE INDEX IF NOT EXISTS idx_site_visits_status ON marketing_site_visits(status);
CREATE INDEX IF NOT EXISTS idx_site_visits_created_by ON marketing_site_visits(created_by);
ALTER TABLE marketing_site_visits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view all site visits" ON marketing_site_visits FOR SELECT USING (true);
CREATE POLICY "Users can insert site visits" ON marketing_site_visits FOR INSERT WITH CHECK (auth.uid() = created_by);
CREATE POLICY "Users can update site visits" ON marketing_site_visits FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Users can delete site visits" ON marketing_site_visits FOR DELETE USING (true);
CREATE OR REPLACE FUNCTION update_marketing_site_visits_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trigger_update_marketing_site_visits_updated_at ON marketing_site_visits;
CREATE TRIGGER trigger_update_marketing_site_visits_updated_at
    BEFORE UPDATE ON marketing_site_visits
    FOR EACH ROW EXECUTE FUNCTION update_marketing_site_visits_updated_at();

-- =============================================================================
-- BEGIN: root/admin_ifsp_employee_master_schema.sql
-- =============================================================================
CREATE TABLE IF NOT EXISTS admin_ifsp_employee_master (
    id bigint generated by default as identity primary key,
    employee_id text not null,
    full_name text not null,
    gender text,
    date_of_joining date not null,
    designation text not null,
    date_of_birth date,
    date_of_anniversary date,
    blood_group text,
    aadhar_no text,
    pan_card_no text,
    religion text,
    father_name text,
    mother_name text,
    spouse_name text,
    son_name text,
    son_dob date,
    daughter_name text,
    address text,
    full_address text,
    personal_no text,
    emergency_no text,
    identification_mark text,
    years_of_experience numeric,
    qualification text,
    attachments text[],
    birthday_reminder boolean default true,
    anniversary_reminder boolean default true,
    department text not null,
    other_experience numeric,
    ifspl_experience numeric,
    date_of_leaving date,
    status text not null default 'Active',
    status_reason text,
    status_changed_by text,
    status_changed_at timestamptz,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    created_by text,
    updated_by text,
    user_id uuid references auth.users(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_admin_ifsp_employee_master_employee_id_user
    ON admin_ifsp_employee_master(user_id, employee_id);

-- =============================================================================
-- BEGIN: root/operations_fire_tender_vehicle_schema.sql
-- =============================================================================
CREATE TABLE IF NOT EXISTS operations_fire_tender_vehicle_drivers (
    id bigint generated by default as identity primary key,
    employee_id text,
    full_name text not null,
    contact_number text,
    email text,
    license_number text,
    license_type text,
    license_expiry_date date,
    department text,
    designation text,
    is_active boolean default true,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);
CREATE TABLE IF NOT EXISTS operations_fire_tender_vehicle_master (
    id bigint generated by default as identity primary key,
    vehicle_type text not null,
    registration_number text not null,
    make text not null,
    model text not null,
    assigned_driver_id bigint references operations_fire_tender_vehicle_drivers(id) on delete set null,
    vehicle_status text not null default 'Available',
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);

-- =============================================================================
-- BEGIN: root/ifsp_employee_master_updated_sample_data.sql
-- =============================================================================
INSERT INTO ifsp_employees (
    employee_id, full_name, gender, date_of_joining, designation, date_of_birth,
    date_of_anniversary, blood_group, aadhar_no, pan_card_no, religion,
    father_name, mother_name, spouse_name, son_name, son_dob, daughter_name,
    address, full_address, personal_no, emergency_no, identification_mark,
    years_of_experience, qualification, attachments, birthday_reminder,
    anniversary_reminder, department, other_experience, ifspl_experience,
    date_of_leaving, status, status_reason, created_by, updated_by, user_id
) VALUES
('EMP001', 'Rajesh Kumar Sharma', 'Male', '2020-01-15', 'Manager', '1985-03-15',
 '2020-01-15', 'A+', '123456789012', 'ABCDE1234F', 'Hindu',
 'Ram Kumar Sharma', 'Sita Devi Sharma', 'Priya Sharma', 'Arjun Sharma', '2010-05-20', 'Kavya Sharma',
 '123 Main Street, Sector 15', '123 Main Street, Sector 15, Gurgaon, Haryana - 122001', '9876543210', '9876543211', 'Mole on left cheek',
 8.5, 'MBA in HR, B.Com, Diploma in Computer Applications', ARRAY['resume.pdf', 'certificates.pdf'], true,
 true, 'HR', 5.0, 3.5, NULL, 'Active', NULL, 'admin@ifsp.com', 'admin@ifsp.com', auth.uid());

-- =============================================================================
-- BEGIN: root/marketing_mail_templates_schema.sql
-- =============================================================================
CREATE TABLE IF NOT EXISTS marketing_mail_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    template_type TEXT NOT NULL DEFAULT 'Subject',
    subject_title TEXT,
    subject_content TEXT,
    terms_and_conditions TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),
    updated_by UUID REFERENCES auth.users(id)
);
ALTER TABLE marketing_mail_templates ENABLE ROW LEVEL SECURITY;

-- =============================================================================
-- BEGIN: root/fix_costing_accessories_rls.sql
-- =============================================================================
ALTER TABLE costing_accessories ADD COLUMN IF NOT EXISTS user_id uuid references auth.users(id);
CREATE INDEX IF NOT EXISTS idx_costing_accessories_user_id ON costing_accessories(user_id);
ALTER TABLE costing_accessories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view their own costing accessories" ON costing_accessories;
DROP POLICY IF EXISTS "Users can insert their own costing accessories" ON costing_accessories;
DROP POLICY IF EXISTS "Users can update their own costing accessories" ON costing_accessories;
DROP POLICY IF EXISTS "Users can delete their own costing accessories" ON costing_accessories;
CREATE POLICY "Authenticated users can view costing accessories" ON costing_accessories FOR SELECT TO authenticated USING (user_id IS NULL OR auth.uid() = user_id);
CREATE POLICY "Authenticated users can insert costing accessories" ON costing_accessories FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update costing accessories" ON costing_accessories FOR UPDATE TO authenticated USING (user_id IS NULL OR auth.uid() = user_id) WITH CHECK (true);
CREATE POLICY "Authenticated users can delete costing accessories" ON costing_accessories FOR DELETE TO authenticated USING (user_id IS NULL OR auth.uid() = user_id);

-- =============================================================================
-- END: Consolidated migrations
-- =============================================================================
-- =============================================================================
-- BEGIN: root/create_quotation_signatures_bucket.sql
-- =============================================================================
-- Instructional SQL reference retained:
-- create policy examples for storage.objects bucket_id = 'quotation-signatures'

-- =============================================================================
-- BEGIN: root/update_costing_sheets_schema.sql
-- =============================================================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'marketing_costing_sheets'
        AND column_name = 'costing_data'
    ) THEN
        ALTER TABLE marketing_costing_sheets
        ADD COLUMN costing_data JSONB;
        COMMENT ON COLUMN marketing_costing_sheets.costing_data IS 'Stores Excel-like costing sheet data with items (columns) and cost heads (rows)';
    END IF;
END $$;

-- =============================================================================
-- BEGIN: root/marketing_internal_quotation_schema_update.sql
-- =============================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_quotations' AND column_name = 'subject_title') THEN
        ALTER TABLE marketing_quotations ADD COLUMN subject_title TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_quotations' AND column_name = 'subject') THEN
        ALTER TABLE marketing_quotations ADD COLUMN subject TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_quotations' AND column_name = 'signed_by') THEN
        ALTER TABLE marketing_quotations ADD COLUMN signed_by TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_quotations' AND column_name = 'signature_path') THEN
        ALTER TABLE marketing_quotations ADD COLUMN signature_path TEXT;
    END IF;
END $$;
COMMENT ON COLUMN marketing_quotations.subject_title IS 'Subject title/header for internal quotations';
COMMENT ON COLUMN marketing_quotations.subject IS 'Subject content/description for internal quotations';
COMMENT ON COLUMN marketing_quotations.signed_by IS 'Name of the person signing the internal quotation';
COMMENT ON COLUMN marketing_quotations.signature_path IS 'Path to the signature image file';

-- =============================================================================
-- BEGIN: root/marketing_expo_seminars_schema_update.sql
-- =============================================================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_attribute
        WHERE attrelid = 'marketing_expo_seminars'::regclass
        AND attname = 'cost_sheet_data'
    ) THEN
        ALTER TABLE marketing_expo_seminars
        ADD COLUMN cost_sheet_data JSONB;
    END IF;
END $$;
COMMENT ON COLUMN marketing_expo_seminars.cost_sheet_data IS 'Stores cost sheet data including items, images, and total amount in JSON format';

-- =============================================================================
-- BEGIN: root/add_client_address_columns.sql
-- =============================================================================
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_clients' AND column_name = 'street_address') THEN
    ALTER TABLE marketing_clients ADD COLUMN street_address TEXT;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_clients' AND column_name = 'zip_code') THEN
    ALTER TABLE marketing_clients ADD COLUMN zip_code TEXT;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_clients' AND column_name = 'contact_numbers') THEN
    ALTER TABLE marketing_clients ADD COLUMN contact_numbers TEXT;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'marketing_clients' AND column_name = 'contact_emails') THEN
    ALTER TABLE marketing_clients ADD COLUMN contact_emails TEXT;
  END IF;
END $$;

-- =============================================================================
-- BEGIN: root/add_missing_columns_marketing_site_visits.sql
-- =============================================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'marketing_site_visits' AND column_name = 'executive_names') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN executive_names TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'marketing_site_visits' AND column_name = 'visitor_name') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN visitor_name TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'marketing_site_visits' AND column_name = 'company_name') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN company_name TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'marketing_site_visits' AND column_name = 'client_name') THEN
    ALTER TABLE marketing_site_visits ADD COLUMN client_name TEXT;
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_marketing_site_visits_visit_date ON marketing_site_visits(visit_date);
CREATE INDEX IF NOT EXISTS idx_marketing_site_visits_status ON marketing_site_visits(status);
CREATE INDEX IF NOT EXISTS idx_marketing_site_visits_client_name ON marketing_site_visits(client_name);

-- =============================================================================
-- BEGIN: root/ifsp_employee_master_schema.sql
-- =============================================================================
CREATE TABLE IF NOT EXISTS ifsp_employees (
    id bigint generated by default as identity primary key,
    employee_id text not null unique,
    first_name text not null,
    last_name text not null,
    email text not null unique,
    phone text,
    date_of_birth date,
    date_of_joining date not null,
    department text not null,
    designation text not null,
    reporting_manager text,
    employment_type text not null default 'Full Time',
    status text not null default 'Active',
    basic_salary numeric,
    address text,
    emergency_contact_name text,
    emergency_contact_phone text,
    emergency_contact_relation text,
    qualifications text,
    skills text,
    previous_experience numeric,
    notes text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);
ALTER TABLE ifsp_employees ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can insert their own employees" ON ifsp_employees FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view their own employees" ON ifsp_employees FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update their own employees" ON ifsp_employees FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own employees" ON ifsp_employees FOR DELETE USING (auth.uid() = user_id);

-- =============================================================================
-- BEGIN: 20260427120500_add_po_received_and_custom_advance_to_po_wo.sql
-- =============================================================================
ALTER TABLE billing.po_wo
  ADD COLUMN IF NOT EXISTS po_received_date date,
  ADD COLUMN IF NOT EXISTS custom_advance_percent text;

-- Shared billing.po_wo: one row shape for all verticals; unused columns stay NULL.
ALTER TABLE billing.po_wo
  ADD COLUMN IF NOT EXISTS po_type text,
  ADD COLUMN IF NOT EXISTS pan_number text,
  ADD COLUMN IF NOT EXISTS contact_email text,
  ADD COLUMN IF NOT EXISTS payment_term_mode text,
  ADD COLUMN IF NOT EXISTS payment_term_days integer,
  ADD COLUMN IF NOT EXISTS advance_percent numeric(18,2);

COMMENT ON COLUMN billing.po_wo.po_type IS 'Same meaning as billing_type: Manpower (Per Day|Monthly|Lump Sum) or RM (Supply|Service); both columns kept in sync on save.';
COMMENT ON COLUMN billing.po_wo.pan_number IS 'Buyer PAN; optional for all verticals.';
COMMENT ON COLUMN billing.po_wo.contact_email IS 'Primary contact email; optional for all verticals.';
COMMENT ON COLUMN billing.po_wo.payment_term_mode IS 'RM-style terms: immediate | days | advance; NULL for Manpower/Training-only rows.';
COMMENT ON COLUMN billing.po_wo.payment_term_days IS 'When payment_term_mode = days.';
COMMENT ON COLUMN billing.po_wo.advance_percent IS 'When payment_term_mode = advance.';

ALTER TABLE billing.po_contact_log
  ADD COLUMN IF NOT EXISTS contact_email text;

COMMENT ON COLUMN billing.po_contact_log.contact_email IS 'Optional email per contact-log row (same as billingApi insert).';

-- Allow both module PO type domains in shared billing.po_wo.
ALTER TABLE billing.po_wo
  DROP CONSTRAINT IF EXISTS billing_po_wo_po_type_check;

ALTER TABLE billing.po_wo
  ADD CONSTRAINT billing_po_wo_po_type_check
  CHECK (
    po_type IS NULL OR
    po_type IN (
      'Per Day', 'Monthly', 'Lump Sum',
      'Supply', 'Service'
    )
  );

-- =============================================================================
-- BEGIN: billing_invoice_buyer_gst_columns.sql
-- CreateInvoice / billingApi persist buyer PIN fields for e-invoice alignment.
-- =============================================================================
ALTER TABLE billing.invoice
  ADD COLUMN IF NOT EXISTS buyer_pin text,
  ADD COLUMN IF NOT EXISTS buyer_pincode text,
  ADD COLUMN IF NOT EXISTS buyer_state_code text;

COMMENT ON COLUMN billing.invoice.buyer_pin IS 'Buyer PIN / location pin text for GST display.';
COMMENT ON COLUMN billing.invoice.buyer_pincode IS 'Buyer PIN code (text).';
COMMENT ON COLUMN billing.invoice.buyer_state_code IS 'Buyer state numeric code.';

-- =============================================================================
-- BEGIN: standardize_po_vertical_bill_to_manp.sql
-- Legacy code BILL → MANP (Manpower); OC numbers aligned with IFSPL-{VERTICAL}-OC-…
-- =============================================================================
UPDATE billing.po_wo
SET vertical = 'MANP'
WHERE upper(trim(coalesce(vertical, ''))) = 'BILL';

UPDATE billing.po_wo
SET oc_number = replace(oc_number, '-BILL-', '-MANP-')
WHERE oc_number IS NOT NULL AND oc_number LIKE '%-BILL-%';

UPDATE billing.invoice
SET oc_number = replace(oc_number, '-BILL-', '-MANP-')
WHERE oc_number IS NOT NULL AND oc_number LIKE '%-BILL-%';

ALTER TABLE billing.po_wo
  ALTER COLUMN vertical SET DEFAULT 'MANP';

-- =============================================================================
-- BEGIN: 20260512100600_software_subscriptions.sql
-- =============================================================================
create table if not exists public.software_subscriptions (
  id uuid primary key default gen_random_uuid(),
  tool_service text not null default '',
  description text,
  purchase_price_first_year numeric(18,2) not null default 0,
  monthly_cost_ongoing numeric(18,2) not null default 0,
  yearly_cost_ongoing numeric(18,2) not null default 0,
  currency text not null default 'INR',
  monthly_cost_inr numeric(18,2) not null default 0,
  yearly_cost_inr numeric(18,2) not null default 0,
  credit_card text,
  invoices text,
  invoice_attachments jsonb not null default '[]'::jsonb,
  billing_type text not null default 'prepaid',
  payment_type text not null default 'Recurring',
  next_payment_date date,
  payment_status text not null default 'pending',
  reminder_days_before integer not null default 7,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint software_subscriptions_payment_status_check
    check (payment_status in ('pending', 'paid', 'overdue', 'cancelled')),
  constraint software_subscriptions_billing_type_check
    check (billing_type in ('prepaid', 'postpaid')),
  constraint software_subscriptions_reminder_days_check
    check (reminder_days_before >= 0)
);

create index if not exists software_subscriptions_next_payment_date_idx
  on public.software_subscriptions (next_payment_date);

create index if not exists software_subscriptions_payment_status_idx
  on public.software_subscriptions (payment_status);

create index if not exists software_subscriptions_created_at_idx
  on public.software_subscriptions (created_at desc);

alter table public.software_subscriptions enable row level security;

drop policy if exists "software_subscriptions_select_super_admin" on public.software_subscriptions;
drop policy if exists "software_subscriptions_insert_super_admin" on public.software_subscriptions;
drop policy if exists "software_subscriptions_update_super_admin" on public.software_subscriptions;
drop policy if exists "software_subscriptions_delete_super_admin" on public.software_subscriptions;

create policy "software_subscriptions_select_super_admin"
  on public.software_subscriptions for select
  to authenticated
  using (public.is_current_user_admin());

create policy "software_subscriptions_insert_super_admin"
  on public.software_subscriptions for insert
  to authenticated
  with check (public.is_current_user_admin());

create policy "software_subscriptions_update_super_admin"
  on public.software_subscriptions for update
  to authenticated
  using (public.is_current_user_admin())
  with check (public.is_current_user_admin());

create policy "software_subscriptions_delete_super_admin"
  on public.software_subscriptions for delete
  to authenticated
  using (public.is_current_user_admin());

drop trigger if exists software_subscriptions_updated_at on public.software_subscriptions;
create trigger software_subscriptions_updated_at
  before update on public.software_subscriptions
  for each row execute function public.set_updated_at();

comment on table public.software_subscriptions is
  'Super Admin-only tracker for software subscription entries, costs, invoices, and payment reminders.';

insert into storage.buckets (id, name, public)
values ('software-subscription-invoices', 'software-subscription-invoices', false)
on conflict (id) do nothing;

drop policy if exists "software_subscription_invoices_select_super_admin" on storage.objects;
drop policy if exists "software_subscription_invoices_insert_super_admin" on storage.objects;
drop policy if exists "software_subscription_invoices_update_super_admin" on storage.objects;
drop policy if exists "software_subscription_invoices_delete_super_admin" on storage.objects;

create policy "software_subscription_invoices_select_super_admin"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'software-subscription-invoices' and public.is_current_user_admin());

create policy "software_subscription_invoices_insert_super_admin"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'software-subscription-invoices' and public.is_current_user_admin());

create policy "software_subscription_invoices_update_super_admin"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'software-subscription-invoices' and public.is_current_user_admin())
  with check (bucket_id = 'software-subscription-invoices' and public.is_current_user_admin());

create policy "software_subscription_invoices_delete_super_admin"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'software-subscription-invoices' and public.is_current_user_admin());

-- =============================================================================
-- BEGIN: 20260512113900_software_subscription_invoice_attachments.sql
-- =============================================================================
alter table public.software_subscriptions
  add column if not exists invoice_attachments jsonb not null default '[]'::jsonb;

-- =============================================================================
-- BEGIN: 20260512114400_software_subscription_billing_type.sql
-- =============================================================================
alter table public.software_subscriptions
  add column if not exists billing_type text not null default 'prepaid';

alter table public.software_subscriptions
  drop constraint if exists software_subscriptions_billing_type_check;

alter table public.software_subscriptions
  add constraint software_subscriptions_billing_type_check
  check (billing_type in ('prepaid', 'postpaid'));

-- =============================================================================
-- END: Consolidated migrations
-- =============================================================================
