import {
  LayoutDashboard,
  Target,
  Contact,
  Users,
  FileText,
  ShoppingCart,
  Calendar,
  Package,
  MapPin,
  Receipt,
  Mail,
  BarChart3,
} from 'lucide-react';

/** Shared marketing sidebar / module nav — keep order in sync with roles.js. */
export const MARKETING_NAV_ITEMS = [
  {
    path: '/app/marketing',
    label: 'Marketing Dashboard',
    subModule: 'marketing.dashboard',
    end: true,
    icon: LayoutDashboard,
    iconClass: 'text-purple-600',
  },
  {
    path: '/app/marketing/lead-dashboard',
    label: 'Lead Dashboard',
    subModule: 'marketing.lead-dashboard',
    icon: Target,
    iconClass: 'text-sky-600',
  },
  {
    path: '/app/marketing/lead-master',
    label: 'Lead Master',
    subModule: 'marketing.lead-master',
    icon: Contact,
    iconClass: 'text-cyan-600',
  },
  {
    path: '/app/marketing/client-master',
    label: 'Client Master',
    subModule: 'marketing.client-master',
    icon: Users,
    iconClass: 'text-indigo-600',
  },
  {
    path: '/app/marketing/enquiry-master',
    label: 'Enquiry Master',
    subModule: 'marketing.enquiry-master',
    icon: FileText,
    iconClass: 'text-accent',
  },
  {
    path: '/app/marketing/quotation-tracker',
    label: 'Quotation Tracker',
    subModule: 'marketing.quotation',
    icon: null,
    iconClass: 'text-green-600',
    useRupee: true,
  },
  {
    path: '/app/marketing/purchase-orders',
    label: 'Purchase Orders',
    subModule: 'marketing.purchase-orders',
    icon: ShoppingCart,
    iconClass: 'text-pink-600',
  },
  {
    path: '/app/marketing/follow-up-planner',
    label: 'Follow-up Planner',
    subModule: 'marketing.follow-up',
    icon: Calendar,
    iconClass: 'text-orange-600',
  },
  {
    path: '/app/marketing/product-catalog',
    label: 'Product Catalogs',
    subModule: 'marketing.product-catalog',
    icon: Package,
    iconClass: 'text-yellow-600',
  },
  {
    path: '/app/marketing/expo-seminar',
    label: 'Expo & Seminar',
    subModule: 'marketing.expo-seminar',
    icon: MapPin,
    iconClass: 'text-accent',
  },
  {
    path: '/app/marketing/gst-upload',
    label: 'GST Documents',
    subModule: 'marketing.gst',
    icon: Receipt,
    iconClass: 'text-teal-600',
  },
  {
    path: '/app/marketing/mail-templates',
    label: 'Marketing Mail Template',
    subModule: 'marketing.mail-template',
    icon: Mail,
    iconClass: 'text-accent',
  },
  {
    path: '/app/marketing/reports-analytics',
    label: 'Reports & Analytics',
    subModule: 'marketing.reports',
    icon: BarChart3,
    iconClass: 'text-accent',
  },
];
