-- Admin > IFSP Employee Master - Database Schema
-- For INDUS ERP CORE. Main page: Admin, Sub page: ifsp-employee-master
-- Table naming: admin_<sub_page> (admin_ifsp_employee_master)

-- ==============================================
-- Table: admin_ifsp_employee_master
-- Purpose: Master list of IFSPL employees (Admin module)
-- ==============================================
CREATE TABLE IF NOT EXISTS admin_ifsp_employee_master (
    id bigint generated by default as identity primary key,

    -- Basic Information
    employee_id text not null,
    full_name text not null,
    gender text,
    date_of_joining date not null,
    designation text not null,
    date_of_birth date,
    date_of_anniversary date,
    blood_group text,

    -- Identity Documents
    aadhar_no text,
    pan_card_no text,
    religion text,

    -- Family Information
    father_name text,
    mother_name text,
    spouse_name text,
    son_name text,
    son_dob date,
    daughter_name text,

    -- Contact Information
    address text,
    full_address text,
    personal_no text,
    emergency_no text,

    -- Physical & Professional
    identification_mark text,
    years_of_experience numeric,
    qualification text,
    attachments text[],

    -- Reminders
    birthday_reminder boolean default true,
    anniversary_reminder boolean default true,

    -- Employment Details
    department text not null,
    other_experience numeric,
    ifspl_experience numeric,
    date_of_leaving date,

    -- Status Management
    status text not null default 'Active',
    status_reason text,
    status_changed_by text,
    status_changed_at timestamptz,

    -- Audit
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    created_by text,
    updated_by text,
    user_id uuid references auth.users(id)
);

-- Unique constraint on employee_id per tenant (user_id)
CREATE UNIQUE INDEX IF NOT EXISTS idx_admin_ifsp_employee_master_employee_id_user
    ON admin_ifsp_employee_master(user_id, employee_id);

-- Enable Row Level Security
ALTER TABLE admin_ifsp_employee_master ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can insert own admin_ifsp_employee_master"
    ON admin_ifsp_employee_master FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view own admin_ifsp_employee_master"
    ON admin_ifsp_employee_master FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update own admin_ifsp_employee_master"
    ON admin_ifsp_employee_master FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own admin_ifsp_employee_master"
    ON admin_ifsp_employee_master FOR DELETE
    USING (auth.uid() = user_id);

-- ==============================================
-- Table: admin_ifsp_employee_master_history
-- Purpose: Status and change history for employee records
-- ==============================================
CREATE TABLE IF NOT EXISTS admin_ifsp_employee_master_history (
    id bigint generated by default as identity primary key,
    master_id bigint not null references admin_ifsp_employee_master(id) on delete cascade,
    field_name text not null,
    old_value text,
    new_value text,
    changed_by text,
    changed_at timestamptz default now(),
    change_reason text,
    user_id uuid references auth.users(id)
);

ALTER TABLE admin_ifsp_employee_master_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own admin_ifsp_employee_master_history"
    ON admin_ifsp_employee_master_history FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own admin_ifsp_employee_master_history"
    ON admin_ifsp_employee_master_history FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- ==============================================
-- Indexes
-- ==============================================
CREATE INDEX IF NOT EXISTS idx_admin_ifsp_emp_master_employee_id ON admin_ifsp_employee_master(employee_id);
CREATE INDEX IF NOT EXISTS idx_admin_ifsp_emp_master_full_name ON admin_ifsp_employee_master(full_name);
CREATE INDEX IF NOT EXISTS idx_admin_ifsp_emp_master_department ON admin_ifsp_employee_master(department);
CREATE INDEX IF NOT EXISTS idx_admin_ifsp_emp_master_status ON admin_ifsp_employee_master(status);
CREATE INDEX IF NOT EXISTS idx_admin_ifsp_emp_master_user_id ON admin_ifsp_employee_master(user_id);
CREATE INDEX IF NOT EXISTS idx_admin_ifsp_emp_master_aadhar ON admin_ifsp_employee_master(aadhar_no);
CREATE INDEX IF NOT EXISTS idx_admin_ifsp_emp_master_pan ON admin_ifsp_employee_master(pan_card_no);
CREATE INDEX IF NOT EXISTS idx_admin_ifsp_emp_master_joining ON admin_ifsp_employee_master(date_of_joining);
CREATE INDEX IF NOT EXISTS idx_admin_ifsp_emp_master_dob ON admin_ifsp_employee_master(date_of_birth);

CREATE INDEX IF NOT EXISTS idx_admin_ifsp_emp_master_history_master_id ON admin_ifsp_employee_master_history(master_id);
CREATE INDEX IF NOT EXISTS idx_admin_ifsp_emp_master_history_changed_at ON admin_ifsp_employee_master_history(changed_at);

-- ==============================================
-- Trigger: log status and key field changes
-- ==============================================
CREATE OR REPLACE FUNCTION admin_ifsp_employee_master_log_changes()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        INSERT INTO admin_ifsp_employee_master_history (master_id, field_name, old_value, new_value, changed_by, change_reason, user_id)
        VALUES (NEW.id, 'status', OLD.status, NEW.status, NEW.updated_by, NEW.status_reason, NEW.user_id);
    END IF;
    IF OLD.full_name IS DISTINCT FROM NEW.full_name THEN
        INSERT INTO admin_ifsp_employee_master_history (master_id, field_name, old_value, new_value, changed_by, user_id)
        VALUES (NEW.id, 'full_name', OLD.full_name, NEW.full_name, NEW.updated_by, NEW.user_id);
    END IF;
    IF OLD.department IS DISTINCT FROM NEW.department THEN
        INSERT INTO admin_ifsp_employee_master_history (master_id, field_name, old_value, new_value, changed_by, user_id)
        VALUES (NEW.id, 'department', OLD.department, NEW.department, NEW.updated_by, NEW.user_id);
    END IF;
    IF OLD.designation IS DISTINCT FROM NEW.designation THEN
        INSERT INTO admin_ifsp_employee_master_history (master_id, field_name, old_value, new_value, changed_by, user_id)
        VALUES (NEW.id, 'designation', OLD.designation, NEW.designation, NEW.updated_by, NEW.user_id);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS admin_ifsp_employee_master_changes_trigger ON admin_ifsp_employee_master;
CREATE TRIGGER admin_ifsp_employee_master_changes_trigger
    AFTER UPDATE ON admin_ifsp_employee_master
    FOR EACH ROW
    EXECUTE FUNCTION admin_ifsp_employee_master_log_changes();

-- ==============================================
-- Comments
-- ==============================================
COMMENT ON TABLE admin_ifsp_employee_master IS 'Admin > IFSP Employee Master: master list of IFSPL employees';
COMMENT ON TABLE admin_ifsp_employee_master_history IS 'Audit history for admin_ifsp_employee_master changes';
