-- Updated IFSPL Employee Master Database Schema
-- For INDUS ERP CORE - Admin Module
-- Based on exact column requirements

-- ==============================================
-- Table: ifsp_employees
-- Purpose: Master database of all IFSPL employees with exact column specifications
-- ==============================================
CREATE TABLE IF NOT EXISTS ifsp_employees (
    id bigint generated by default as identity primary key,
    
    -- Basic Information
    employee_id text not null unique,
    timestamp timestamptz default now(),
    full_name text not null,
    gender text, -- Male, Female, Other
    date_of_joining date not null,
    designation text not null,
    date_of_birth date,
    date_of_anniversary date,
    blood_group text, -- A+, A-, B+, B-, AB+, AB-, O+, O-
    
    -- Identity Documents
    aadhar_no text unique,
    pan_card_no text unique,
    religion text,
    
    -- Family Information
    father_name text,
    mother_name text,
    spouse_name text,
    son_name text,
    son_dob date, -- Son's Date of Birth
    daughter_name text,
    
    -- Contact Information
    address text,
    full_address text,
    personal_no text,
    emergency_no text,
    
    -- Physical & Professional
    identification_mark text,
    years_of_experience numeric, -- Total years of experience
    qualification text,
    attachments text[], -- Array of attachment URLs
    
    -- Reminders
    birthday_reminder boolean default true,
    anniversary_reminder boolean default true,
    
    -- Employment Details
    department text not null,
    other_experience numeric, -- Experience outside IFSPL
    ifspl_experience numeric, -- Experience within IFSPL
    date_of_leaving date, -- DOL - Date of Leaving
    
    -- Status Management
    status text not null default 'Active', -- Active, Inactive
    status_reason text, -- Reason for status change
    status_changed_by text, -- Who changed the status
    status_changed_at timestamptz, -- When status was changed
    
    -- Audit Fields
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    created_by text,
    updated_by text,
    user_id uuid references auth.users(id) -- 🔑 link to Supabase Auth user
);

-- Enable Row Level Security
ALTER TABLE ifsp_employees ENABLE ROW LEVEL SECURITY;

-- RLS Policies for ifsp_employees
CREATE POLICY "Users can insert their own employees"
    ON ifsp_employees FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own employees"
    ON ifsp_employees FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own employees"
    ON ifsp_employees FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own employees"
    ON ifsp_employees FOR DELETE
    USING (auth.uid() = user_id);

-- ==============================================
-- Table: ifsp_employee_history
-- Purpose: Track all changes to employee records
-- ==============================================
CREATE TABLE IF NOT EXISTS ifsp_employee_history (
    id bigint generated by default as identity primary key,
    employee_id bigint not null references ifsp_employees(id) on delete cascade,
    field_name text not null,
    old_value text,
    new_value text,
    changed_by text not null,
    changed_at timestamptz default now(),
    change_reason text,
    user_id uuid references auth.users(id)
);

-- Enable Row Level Security for history
ALTER TABLE ifsp_employee_history ENABLE ROW LEVEL SECURITY;

-- RLS Policies for history
CREATE POLICY "Users can view their own employee history"
    ON ifsp_employee_history FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own employee history"
    ON ifsp_employee_history FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- ==============================================
-- Indexes for Performance
-- ==============================================

-- Indexes for ifsp_employees
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_employee_id ON ifsp_employees(employee_id);
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_full_name ON ifsp_employees(full_name);
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_department ON ifsp_employees(department);
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_status ON ifsp_employees(status);
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_user_id ON ifsp_employees(user_id);
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_aadhar ON ifsp_employees(aadhar_no);
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_pan ON ifsp_employees(pan_card_no);
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_joining ON ifsp_employees(date_of_joining);
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_dob ON ifsp_employees(date_of_birth);

-- Indexes for history
CREATE INDEX IF NOT EXISTS idx_employee_history_employee_id ON ifsp_employee_history(employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_history_changed_at ON ifsp_employee_history(changed_at);

-- ==============================================
-- Functions for Employee Management
-- ==============================================

-- Function to log employee changes
CREATE OR REPLACE FUNCTION log_employee_changes()
RETURNS TRIGGER AS $$
BEGIN
    -- Log changes for each field
    IF OLD.full_name IS DISTINCT FROM NEW.full_name THEN
        INSERT INTO ifsp_employee_history (employee_id, field_name, old_value, new_value, changed_by, user_id)
        VALUES (NEW.id, 'full_name', OLD.full_name, NEW.full_name, NEW.updated_by, NEW.user_id);
    END IF;
    
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        INSERT INTO ifsp_employee_history (employee_id, field_name, old_value, new_value, changed_by, change_reason, user_id)
        VALUES (NEW.id, 'status', OLD.status, NEW.status, NEW.updated_by, NEW.status_reason, NEW.user_id);
    END IF;
    
    IF OLD.department IS DISTINCT FROM NEW.department THEN
        INSERT INTO ifsp_employee_history (employee_id, field_name, old_value, new_value, changed_by, user_id)
        VALUES (NEW.id, 'department', OLD.department, NEW.department, NEW.updated_by, NEW.user_id);
    END IF;
    
    IF OLD.designation IS DISTINCT FROM NEW.designation THEN
        INSERT INTO ifsp_employee_history (employee_id, field_name, old_value, new_value, changed_by, user_id)
        VALUES (NEW.id, 'designation', OLD.designation, NEW.designation, NEW.updated_by, NEW.user_id);
    END IF;
    
    -- Add more field comparisons as needed
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for logging changes
CREATE TRIGGER employee_changes_trigger
    AFTER UPDATE ON ifsp_employees
    FOR EACH ROW
    EXECUTE FUNCTION log_employee_changes();

-- Function to get employee count by department
CREATE OR REPLACE FUNCTION get_employee_count_by_department()
RETURNS TABLE (
    department text,
    active_count bigint,
    inactive_count bigint,
    total_count bigint
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        ie.department,
        COUNT(CASE WHEN ie.status = 'Active' THEN 1 END) as active_count,
        COUNT(CASE WHEN ie.status = 'Inactive' THEN 1 END) as inactive_count,
        COUNT(*) as total_count
    FROM ifsp_employees ie
    WHERE ie.user_id = auth.uid()
    GROUP BY ie.department
    ORDER BY total_count DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get employees with upcoming birthdays
CREATE OR REPLACE FUNCTION get_upcoming_birthdays(days_ahead integer DEFAULT 30)
RETURNS TABLE (
    employee_id text,
    full_name text,
    date_of_birth date,
    days_until_birthday integer
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        ie.employee_id,
        ie.full_name,
        ie.date_of_birth,
        EXTRACT(DAY FROM (ie.date_of_birth + INTERVAL '1 year' * (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM ie.date_of_birth)) - CURRENT_DATE))::integer as days_until_birthday
    FROM ifsp_employees ie
    WHERE ie.user_id = auth.uid()
    AND ie.status = 'Active'
    AND ie.birthday_reminder = true
    AND ie.date_of_birth IS NOT NULL
    ORDER BY days_until_birthday;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==============================================
-- Comments for Documentation
-- ==============================================

COMMENT ON TABLE ifsp_employees IS 'Master database of all IFSPL employees with complete personal and employment information';
COMMENT ON TABLE ifsp_employee_history IS 'Audit trail for all changes made to employee records';

COMMENT ON COLUMN ifsp_employees.employee_id IS 'Unique employee identifier';
COMMENT ON COLUMN ifsp_employees.timestamp IS 'Record creation timestamp';
COMMENT ON COLUMN ifsp_employees.full_name IS 'Complete name of the employee';
COMMENT ON COLUMN ifsp_employees.gender IS 'Gender of the employee';
COMMENT ON COLUMN ifsp_employees.date_of_joining IS 'Date when employee joined IFSPL';
COMMENT ON COLUMN ifsp_employees.designation IS 'Current job designation';
COMMENT ON COLUMN ifsp_employees.date_of_birth IS 'Employee date of birth';
COMMENT ON COLUMN ifsp_employees.date_of_anniversary IS 'Work anniversary date';
COMMENT ON COLUMN ifsp_employees.blood_group IS 'Blood group of the employee';
COMMENT ON COLUMN ifsp_employees.aadhar_no IS 'Aadhar card number';
COMMENT ON COLUMN ifsp_employees.pan_card_no IS 'PAN card number';
COMMENT ON COLUMN ifsp_employees.religion IS 'Religious affiliation';
COMMENT ON COLUMN ifsp_employees.father_name IS 'Father name';
COMMENT ON COLUMN ifsp_employees.mother_name IS 'Mother name';
COMMENT ON COLUMN ifsp_employees.spouse_name IS 'Spouse name';
COMMENT ON COLUMN ifsp_employees.son_name IS 'Son name';
COMMENT ON COLUMN ifsp_employees.son_dob IS 'Son date of birth';
COMMENT ON COLUMN ifsp_employees.daughter_name IS 'Daughter name';
COMMENT ON COLUMN ifsp_employees.address IS 'Current address';
COMMENT ON COLUMN ifsp_employees.full_address IS 'Complete address with all details';
COMMENT ON COLUMN ifsp_employees.personal_no IS 'Personal contact number';
COMMENT ON COLUMN ifsp_employees.emergency_no IS 'Emergency contact number';
COMMENT ON COLUMN ifsp_employees.identification_mark IS 'Physical identification marks';
COMMENT ON COLUMN ifsp_employees.years_of_experience IS 'Total years of work experience';
COMMENT ON COLUMN ifsp_employees.qualification IS 'Educational qualifications';
COMMENT ON COLUMN ifsp_employees.attachments IS 'Array of document attachment URLs';
COMMENT ON COLUMN ifsp_employees.birthday_reminder IS 'Enable birthday reminders';
COMMENT ON COLUMN ifsp_employees.anniversary_reminder IS 'Enable anniversary reminders';
COMMENT ON COLUMN ifsp_employees.department IS 'Current department';
COMMENT ON COLUMN ifsp_employees.other_experience IS 'Experience outside IFSPL';
COMMENT ON COLUMN ifsp_employees.ifspl_experience IS 'Experience within IFSPL';
COMMENT ON COLUMN ifsp_employees.date_of_leaving IS 'Date of leaving (DOL)';
COMMENT ON COLUMN ifsp_employees.status IS 'Current status (Active/Inactive)';
COMMENT ON COLUMN ifsp_employees.status_reason IS 'Reason for status change';
COMMENT ON COLUMN ifsp_employees.status_changed_by IS 'Who changed the status';
COMMENT ON COLUMN ifsp_employees.status_changed_at IS 'When status was changed';
