-- IFSPL Employee Master Database Schema
-- For INDUS ERP CORE - Admin Module

-- ==============================================
-- Table: ifsp_employees
-- Purpose: Master database of all IFSPL employees
-- ==============================================
CREATE TABLE IF NOT EXISTS ifsp_employees (
    id bigint generated by default as identity primary key,
    employee_id text not null unique,
    first_name text not null,
    last_name text not null,
    email text not null unique,
    phone text,
    date_of_birth date,
    date_of_joining date not null,
    department text not null,
    designation text not null,
    reporting_manager text,
    employment_type text not null default 'Full Time', -- Full Time, Part Time, Contract, Intern, Consultant
    status text not null default 'Active', -- Active, Inactive, Terminated, On Leave
    basic_salary numeric,
    address text,
    emergency_contact_name text,
    emergency_contact_phone text,
    emergency_contact_relation text,
    qualifications text,
    skills text,
    previous_experience numeric, -- in years
    notes text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id) -- 🔑 link to Supabase Auth user
);

-- Enable Row Level Security
ALTER TABLE ifsp_employees ENABLE ROW LEVEL SECURITY;

-- RLS Policies for ifsp_employees
CREATE POLICY "Users can insert their own employees"
    ON ifsp_employees FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own employees"
    ON ifsp_employees FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own employees"
    ON ifsp_employees FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own employees"
    ON ifsp_employees FOR DELETE
    USING (auth.uid() = user_id);

-- ==============================================
-- Indexes for Performance
-- ==============================================

-- Indexes for ifsp_employees
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_employee_id ON ifsp_employees(employee_id);
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_email ON ifsp_employees(email);
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_department ON ifsp_employees(department);
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_status ON ifsp_employees(status);
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_user_id ON ifsp_employees(user_id);
CREATE INDEX IF NOT EXISTS idx_ifsp_employees_name ON ifsp_employees(first_name, last_name);

-- ==============================================
-- Functions for Employee Management
-- ==============================================

-- Function to get employee count by department
CREATE OR REPLACE FUNCTION get_employee_count_by_department()
RETURNS TABLE (
    department text,
    employee_count bigint
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        ie.department,
        COUNT(*) as employee_count
    FROM ifsp_employees ie
    WHERE ie.user_id = auth.uid()
    AND ie.status = 'Active'
    GROUP BY ie.department
    ORDER BY employee_count DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get employees by status
CREATE OR REPLACE FUNCTION get_employees_by_status(emp_status text DEFAULT 'Active')
RETURNS TABLE (
    id bigint,
    employee_id text,
    first_name text,
    last_name text,
    email text,
    department text,
    designation text,
    status text
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        ie.id,
        ie.employee_id,
        ie.first_name,
        ie.last_name,
        ie.email,
        ie.department,
        ie.designation,
        ie.status
    FROM ifsp_employees ie
    WHERE ie.user_id = auth.uid()
    AND ie.status = emp_status
    ORDER BY ie.first_name, ie.last_name;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==============================================
-- Comments for Documentation
-- ==============================================

COMMENT ON TABLE ifsp_employees IS 'Master database of all IFSPL employees with complete personal and employment information';
COMMENT ON COLUMN ifsp_employees.employee_id IS 'Unique employee identifier';
COMMENT ON COLUMN ifsp_employees.employment_type IS 'Type of employment (Full Time, Part Time, Contract, Intern, Consultant)';
COMMENT ON COLUMN ifsp_employees.status IS 'Current employment status (Active, Inactive, Terminated, On Leave)';
COMMENT ON COLUMN ifsp_employees.basic_salary IS 'Basic salary amount in local currency';
COMMENT ON COLUMN ifsp_employees.previous_experience IS 'Previous work experience in years';
COMMENT ON COLUMN ifsp_employees.qualifications IS 'Educational qualifications and certifications';
COMMENT ON COLUMN ifsp_employees.skills IS 'Technical and soft skills';
COMMENT ON COLUMN ifsp_employees.notes IS 'Additional notes or comments about the employee';

