-- Missing Database Tables for ERP Modules
-- These tables are referenced in the frontend but don't exist in the database

-- ==============================================
-- Table: accessories
-- Purpose: Master data for accessories (name, description)
-- ==============================================
CREATE TABLE IF NOT EXISTS accessories (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id) -- 🔑 link to Supabase Auth user
);

-- Enable Row Level Security
ALTER TABLE accessories ENABLE ROW LEVEL SECURITY;

-- RLS Policies for accessories
CREATE POLICY "Users can insert their own accessories"
    ON accessories FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own accessories"
    ON accessories FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own accessories"
    ON accessories FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own accessories"
    ON accessories FOR DELETE
    USING (auth.uid() = user_id);

-- ==============================================
-- Table: costing_accessories
-- Purpose: Accessories costing per tender (qty, price)
-- ==============================================
CREATE TABLE IF NOT EXISTS costing_accessories (
    id bigint generated by default as identity primary key,
    tender_id bigint not null references tenders(id) on delete cascade,
    accessory_id bigint not null references accessories(id) on delete cascade,
    qty numeric default 0,
    price numeric default 0,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id) -- 🔑 link to Supabase Auth user
);

-- Enable Row Level Security
ALTER TABLE costing_accessories ENABLE ROW LEVEL SECURITY;

-- RLS Policies for costing_accessories
CREATE POLICY "Users can insert their own costing accessories"
    ON costing_accessories FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own costing accessories"
    ON costing_accessories FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own costing accessories"
    ON costing_accessories FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own costing accessories"
    ON costing_accessories FOR DELETE
    USING (auth.uid() = user_id);

-- Unique constraint to prevent duplicate accessories per tender
CREATE UNIQUE INDEX IF NOT EXISTS unique_accessory_per_tender
    ON costing_accessories(tender_id, accessory_id);

-- ==============================================
-- Table: costing_summary
-- Purpose: Store net total checklist items and calculations
-- ==============================================
CREATE TABLE IF NOT EXISTS costing_summary (
    id bigint generated by default as identity primary key,
    tender_id bigint not null references tenders(id) on delete cascade,
    component text not null,
    unit_cost numeric default 0,
    unit_rate numeric default 0,
    qty numeric default 1,
    total numeric default 0,
    include boolean default true,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id) -- 🔑 link to Supabase Auth user
);

-- Enable Row Level Security
ALTER TABLE costing_summary ENABLE ROW LEVEL SECURITY;

-- RLS Policies for costing_summary
CREATE POLICY "Users can insert their own costing summary"
    ON costing_summary FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own costing summary"
    ON costing_summary FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own costing summary"
    ON costing_summary FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own costing summary"
    ON costing_summary FOR DELETE
    USING (auth.uid() = user_id);

-- Unique constraint to prevent duplicate components per tender
CREATE UNIQUE INDEX IF NOT EXISTS unique_component_per_tender
    ON costing_summary(tender_id, component);

-- ==============================================
-- Table: quotation_templates
-- Purpose: Store quotation templates with subject and body content
-- ==============================================
CREATE TABLE IF NOT EXISTS quotation_templates (
    id bigint generated by default as identity primary key,
    name text not null,
    type text not null default 'Quotation Template',
    subject text,
    content text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id) -- 🔑 link to Supabase Auth user
);

-- Enable Row Level Security
ALTER TABLE quotation_templates ENABLE ROW LEVEL SECURITY;

-- RLS Policies for quotation_templates
CREATE POLICY "Users can insert their own quotation templates"
    ON quotation_templates FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own quotation templates"
    ON quotation_templates FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own quotation templates"
    ON quotation_templates FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own quotation templates"
    ON quotation_templates FOR DELETE
    USING (auth.uid() = user_id);

-- ==============================================
-- Table: approved_quotation_items
-- Purpose: Store items approved for quotation from costing sheet
-- ==============================================
CREATE TABLE IF NOT EXISTS approved_quotation_items (
    id bigint generated by default as identity primary key,
    tender_id bigint not null references tenders(id) on delete cascade,
    component text not null,
    unit_cost numeric default 0,
    unit_rate numeric default 0,
    qty numeric default 1,
    total numeric default 0,
    include boolean default true,
    approved_at timestamptz default now(),
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id) -- 🔑 link to Supabase Auth user
);

-- Enable Row Level Security
ALTER TABLE approved_quotation_items ENABLE ROW LEVEL SECURITY;

-- RLS Policies for approved_quotation_items
CREATE POLICY "Users can insert their own approved quotation items"
    ON approved_quotation_items FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own approved quotation items"
    ON approved_quotation_items FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own approved quotation items"
    ON approved_quotation_items FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own approved quotation items"
    ON approved_quotation_items FOR DELETE
    USING (auth.uid() = user_id);

-- Unique constraint to prevent duplicate components per tender
CREATE UNIQUE INDEX IF NOT EXISTS unique_approved_component_per_tender
    ON approved_quotation_items(tender_id, component);

-- ==============================================
-- Table: app_users (if not exists)
-- Purpose: User profile information
-- ==============================================
CREATE TABLE IF NOT EXISTS app_users (
    id uuid primary key references auth.users(id) on delete cascade,
    email text,
    full_name text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- Enable Row Level Security
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;

-- RLS Policies for app_users
CREATE POLICY "Users can view their own profile"
    ON app_users FOR SELECT
    USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile"
    ON app_users FOR UPDATE
    USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile"
    ON app_users FOR INSERT
    WITH CHECK (auth.uid() = id);

-- ==============================================
-- Additional Indexes for Performance
-- ==============================================

-- Index for faster queries on costing_accessories
CREATE INDEX IF NOT EXISTS idx_costing_accessories_tender_id 
    ON costing_accessories(tender_id);

CREATE INDEX IF NOT EXISTS idx_costing_accessories_accessory_id 
    ON costing_accessories(accessory_id);

-- Index for faster queries on accessories
CREATE INDEX IF NOT EXISTS idx_accessories_user_id 
    ON accessories(user_id);

-- Index for faster queries on costing_rows
CREATE INDEX IF NOT EXISTS idx_costing_rows_tender_id 
    ON costing_rows(tender_id);

CREATE INDEX IF NOT EXISTS idx_costing_rows_user_id 
    ON costing_rows(user_id);

-- ==============================================
-- Comments for Documentation
-- ==============================================

COMMENT ON TABLE accessories IS 'Master data for accessories with name and description';
COMMENT ON TABLE costing_accessories IS 'Accessories costing per tender with quantity and price';
COMMENT ON TABLE app_users IS 'User profile information linked to auth.users';

COMMENT ON COLUMN accessories.name IS 'Name of the accessory';
COMMENT ON COLUMN accessories.description IS 'Detailed description of the accessory';
COMMENT ON COLUMN costing_accessories.qty IS 'Quantity of the accessory for this tender';
COMMENT ON COLUMN costing_accessories.price IS 'Unit price of the accessory for this tender';
