-- Operations > Fire Tender Vehicle Management - Database Schema
-- For INDUS ERP CORE. Main page: Operations, Sub page: fire-tender-vehicle-management
-- Table naming: operations_fire_tender_vehicle_*

-- ==============================================
-- 1. operations_fire_tender_vehicle_drivers
-- (Created first - referenced by master)
-- ==============================================
CREATE TABLE IF NOT EXISTS operations_fire_tender_vehicle_drivers (
    id bigint generated by default as identity primary key,
    employee_id text,
    full_name text not null,
    contact_number text,
    email text,
    license_number text,
    license_type text,
    license_expiry_date date,
    department text,
    designation text,
    is_active boolean default true,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);

ALTER TABLE operations_fire_tender_vehicle_drivers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert own operations_fire_tender_vehicle_drivers"
    ON operations_fire_tender_vehicle_drivers FOR INSERT
    WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own operations_fire_tender_vehicle_drivers"
    ON operations_fire_tender_vehicle_drivers FOR SELECT
    USING (auth.uid() = user_id);
CREATE POLICY "Users can update own operations_fire_tender_vehicle_drivers"
    ON operations_fire_tender_vehicle_drivers FOR UPDATE
    USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own operations_fire_tender_vehicle_drivers"
    ON operations_fire_tender_vehicle_drivers FOR DELETE
    USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_oftv_drivers_employee_id ON operations_fire_tender_vehicle_drivers(employee_id);
CREATE INDEX IF NOT EXISTS idx_oftv_drivers_active ON operations_fire_tender_vehicle_drivers(is_active);
CREATE INDEX IF NOT EXISTS idx_oftv_drivers_user_id ON operations_fire_tender_vehicle_drivers(user_id);

-- ==============================================
-- 2. operations_fire_tender_vehicle_master
-- ==============================================
CREATE TABLE IF NOT EXISTS operations_fire_tender_vehicle_master (
    id bigint generated by default as identity primary key,
    vehicle_type text not null,
    registration_number text not null,
    chassis_number text,
    engine_number text,
    make text not null,
    model text not null,
    year_of_manufacture integer,
    date_of_purchase date,
    date_of_commissioning date,
    assigned_location text,
    assigned_site text,
    assigned_department text,
    assigned_driver_id bigint references operations_fire_tender_vehicle_drivers(id) on delete set null,
    vehicle_status text not null default 'Available',
    current_odometer_reading numeric default 0,
    last_service_date date,
    next_service_due date,
    remarks text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_oftv_master_reg_user ON operations_fire_tender_vehicle_master(user_id, registration_number);

ALTER TABLE operations_fire_tender_vehicle_master ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert own operations_fire_tender_vehicle_master"
    ON operations_fire_tender_vehicle_master FOR INSERT
    WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own operations_fire_tender_vehicle_master"
    ON operations_fire_tender_vehicle_master FOR SELECT
    USING (auth.uid() = user_id);
CREATE POLICY "Users can update own operations_fire_tender_vehicle_master"
    ON operations_fire_tender_vehicle_master FOR UPDATE
    USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own operations_fire_tender_vehicle_master"
    ON operations_fire_tender_vehicle_master FOR DELETE
    USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_oftv_master_registration ON operations_fire_tender_vehicle_master(registration_number);
CREATE INDEX IF NOT EXISTS idx_oftv_master_status ON operations_fire_tender_vehicle_master(vehicle_status);
CREATE INDEX IF NOT EXISTS idx_oftv_master_type ON operations_fire_tender_vehicle_master(vehicle_type);
CREATE INDEX IF NOT EXISTS idx_oftv_master_user_id ON operations_fire_tender_vehicle_master(user_id);

-- ==============================================
-- 3. operations_fire_tender_vehicle_documents
-- ==============================================
CREATE TABLE IF NOT EXISTS operations_fire_tender_vehicle_documents (
    id bigint generated by default as identity primary key,
    vehicle_id bigint not null references operations_fire_tender_vehicle_master(id) on delete cascade,
    document_type text not null,
    document_number text,
    issue_date date,
    expiry_date date not null,
    provider text,
    premium_amount numeric,
    file_url text,
    alert_status text default 'Active',
    remarks text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);

ALTER TABLE operations_fire_tender_vehicle_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert own operations_fire_tender_vehicle_documents"
    ON operations_fire_tender_vehicle_documents FOR INSERT
    WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own operations_fire_tender_vehicle_documents"
    ON operations_fire_tender_vehicle_documents FOR SELECT
    USING (auth.uid() = user_id);
CREATE POLICY "Users can update own operations_fire_tender_vehicle_documents"
    ON operations_fire_tender_vehicle_documents FOR UPDATE
    USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own operations_fire_tender_vehicle_documents"
    ON operations_fire_tender_vehicle_documents FOR DELETE
    USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_oftv_documents_vehicle_id ON operations_fire_tender_vehicle_documents(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_oftv_documents_expiry ON operations_fire_tender_vehicle_documents(expiry_date);
CREATE INDEX IF NOT EXISTS idx_oftv_documents_type ON operations_fire_tender_vehicle_documents(document_type);
CREATE INDEX IF NOT EXISTS idx_oftv_documents_alert ON operations_fire_tender_vehicle_documents(alert_status);

-- ==============================================
-- 4. operations_fire_tender_vehicle_maintenance
-- ==============================================
CREATE TABLE IF NOT EXISTS operations_fire_tender_vehicle_maintenance (
    id bigint generated by default as identity primary key,
    vehicle_id bigint not null references operations_fire_tender_vehicle_master(id) on delete cascade,
    service_date date not null,
    vendor text not null,
    service_type text,
    cost numeric not null,
    odometer_reading numeric,
    nature_of_repair text,
    parts_replaced text,
    next_service_due date,
    remarks text,
    attachment_url text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);

ALTER TABLE operations_fire_tender_vehicle_maintenance ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert own operations_fire_tender_vehicle_maintenance"
    ON operations_fire_tender_vehicle_maintenance FOR INSERT
    WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own operations_fire_tender_vehicle_maintenance"
    ON operations_fire_tender_vehicle_maintenance FOR SELECT
    USING (auth.uid() = user_id);
CREATE POLICY "Users can update own operations_fire_tender_vehicle_maintenance"
    ON operations_fire_tender_vehicle_maintenance FOR UPDATE
    USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own operations_fire_tender_vehicle_maintenance"
    ON operations_fire_tender_vehicle_maintenance FOR DELETE
    USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_oftv_maintenance_vehicle_id ON operations_fire_tender_vehicle_maintenance(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_oftv_maintenance_date ON operations_fire_tender_vehicle_maintenance(service_date);
CREATE INDEX IF NOT EXISTS idx_oftv_maintenance_next_due ON operations_fire_tender_vehicle_maintenance(next_service_due);

-- ==============================================
-- 5. operations_fire_tender_vehicle_trips
-- ==============================================
CREATE TABLE IF NOT EXISTS operations_fire_tender_vehicle_trips (
    id bigint generated by default as identity primary key,
    vehicle_id bigint not null references operations_fire_tender_vehicle_master(id) on delete cascade,
    trip_purpose text not null,
    issued_to_name text not null,
    issued_to_department text,
    issued_to_contact text,
    start_date_time timestamptz not null,
    end_date_time timestamptz,
    origin_location text,
    destination_location text,
    odometer_start numeric,
    odometer_end numeric,
    fuel_added numeric default 0,
    fuel_cost numeric default 0,
    trip_status text default 'Active',
    approved_by text,
    approval_date timestamptz,
    remarks text,
    digital_signature_url text,
    attachments text[],
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);

ALTER TABLE operations_fire_tender_vehicle_trips ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert own operations_fire_tender_vehicle_trips"
    ON operations_fire_tender_vehicle_trips FOR INSERT
    WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own operations_fire_tender_vehicle_trips"
    ON operations_fire_tender_vehicle_trips FOR SELECT
    USING (auth.uid() = user_id);
CREATE POLICY "Users can update own operations_fire_tender_vehicle_trips"
    ON operations_fire_tender_vehicle_trips FOR UPDATE
    USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own operations_fire_tender_vehicle_trips"
    ON operations_fire_tender_vehicle_trips FOR DELETE
    USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_oftv_trips_vehicle_id ON operations_fire_tender_vehicle_trips(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_oftv_trips_status ON operations_fire_tender_vehicle_trips(trip_status);
CREATE INDEX IF NOT EXISTS idx_oftv_trips_start_date ON operations_fire_tender_vehicle_trips(start_date_time);
CREATE INDEX IF NOT EXISTS idx_oftv_trips_purpose ON operations_fire_tender_vehicle_trips(trip_purpose);

-- ==============================================
-- Comments
-- ==============================================
COMMENT ON TABLE operations_fire_tender_vehicle_drivers IS 'Operations > Fire Tender Vehicle: drivers for vehicle assignment';
COMMENT ON TABLE operations_fire_tender_vehicle_master IS 'Operations > Fire Tender Vehicle: master vehicle list';
COMMENT ON TABLE operations_fire_tender_vehicle_documents IS 'Operations > Fire Tender Vehicle: documents with expiry tracking';
COMMENT ON TABLE operations_fire_tender_vehicle_maintenance IS 'Operations > Fire Tender Vehicle: maintenance records';
COMMENT ON TABLE operations_fire_tender_vehicle_trips IS 'Operations > Fire Tender Vehicle: trip/usage tracking';
