-- Table for Main Components & Sub Categories
create table main_components (
  id bigint generated by default as identity primary key,
  main_component text not null,
  sub_category1 text,
  sub_category2 text,
  sub_category3 text,
  sub_category4 text,
  sub_category5 text,
  created_at timestamptz default now(),
  user_id uuid references auth.users(id) -- 🔑 link to Supabase Auth user
);
alter table main_components enable row level security;

-- Allow INSERT only for logged-in users (their user_id must match)
create policy "Users can insert their own data"
on main_components for insert
with check (auth.uid() = user_id);

-- Allow SELECT only their own rows
create policy "Users can view their own data"
on main_components for select
using (auth.uid() = user_id);

-- Allow UPDATE only their own rows
create policy "Users can update their own data"
on main_components for update
using (auth.uid() = user_id);

-- Allow DELETE only their own rows
create policy "Users can delete their own data"
on main_components for delete
using (auth.uid() = user_id);


-- Table for Tenders
create table tenders (
  id bigint generated by default as identity primary key,
  client text,
  phone text,
  email text,
  street text,
  street2 text,
  zip text,
  city text,
  state text,
  country text,
  source text,
  type_of_tender text,
  mode_of_tender text,
  vehicle_type text,
  tender_id_available boolean,
  publish_date date,
  due_date date,
  estimation text,
  description text,
  handled_by text,
  authorization_to text,
  status text,
  tender_number text,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  enquiry_number text,
  user_id uuid references auth.users(id) -- 🔑 link to Supabase Auth user
);

-- Enable Row Level Security
alter table tenders enable row level security;

-- Allow INSERT only for logged-in users (must insert their own user_id)
create policy "Users can insert their own tenders"
on tenders for insert
with check (auth.uid() = user_id);

-- Allow SELECT only their own tenders
create policy "Users can view their own tenders"
on tenders for select
using (auth.uid() = user_id);

-- Allow UPDATE only their own tenders
create policy "Users can update their own tenders"
on tenders for update
using (auth.uid() = user_id);

-- Allow DELETE only their own tenders
create policy "Users can delete their own tenders"
on tenders for delete
using (auth.uid() = user_id);


-- ///////////////////////////////////////////////////////////////////////////////////////

  -- Create costing_rows table (matching tenders.id bigint)
  create table if not exists costing_rows (
    id bigserial primary key,
    tender_id bigint not null references tenders(id) on delete cascade,
    main_component text not null,
    sub_category1 text,
    sub_category2 text,
    sub_category3 text,
    sub_category4 text,
    sub_category5 text,
    manual_sub text,
    weight numeric,
    labour numeric,
    unit_cost numeric,
    qty numeric,
    remark text,
    total numeric, -- store calculated total for that row
    created_at timestamptz default now(),
    user_id uuid references auth.users(id)
  );

  -- Enable row level security
  alter table costing_rows enable row level security;

  -- Allow INSERT only for logged-in users (their user_id must match)
  create policy "Users can insert their own costing rows"
    on costing_rows for insert
    with check (auth.uid() = user_id);

  -- Allow SELECT only for their own rows
  create policy "Users can view their own costing rows"
    on costing_rows for select
    using (auth.uid() = user_id);

  -- Allow UPDATE only their own rows
  create policy "Users can update their own costing rows"
    on costing_rows for update
    using (auth.uid() = user_id);

  -- Allow DELETE only their own rows
  create policy "Users can delete their own costing rows"
    on costing_rows for delete
    using (auth.uid() = user_id);

  -- ..............................................
  ALTER TABLE costing_rows
  ALTER COLUMN tender_id TYPE bigint USING tender_id::bigint;
  -- ..............................................
  -- Create moc_prices table with BIGINT tender_id
CREATE TABLE IF NOT EXISTS moc_prices (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tender_id bigint NOT NULL REFERENCES tenders(id) ON DELETE CASCADE,
    moc text NOT NULL,
    unit text NOT NULL,
    price numeric,
    inserted_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Ensure each MOC is unique per tender
CREATE UNIQUE INDEX IF NOT EXISTS unique_moc_per_tender
ON moc_prices(moc, tender_id);


-- /////////////////////////////////////////////////////////////
-- Table: manpower_enquiries
create table if not exists public.manpower_enquiries (
    id uuid default gen_random_uuid() primary key,
    client text not null,
    phone text,
    email text,
    street text,
    street2 text,
    city text,
    state text,
    zip text,
    country text,
    priority int default 1,
    source text default 'Mail',
    due_date date,
    rfq_available boolean default false,
    project_estimation text,
    duration jsonb, -- { days, months, years }
    documents text, -- store file url/path from Supabase Storage
    manpower_required text,
    fire_tender_required boolean default false,
    contacts jsonb, -- array of contact objects
    handled_by text,
    authorization_to text,
    enquiry_number text,
    status text default 'Pending',
    user_id uuid references auth.users(id), -- 🔑 link to Supabase Auth user
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- Enable Row Level Security
alter table public.manpower_enquiries enable row level security;

-- INSERT: Users can insert their own enquiries
create policy "Users can insert their own enquiries"
on public.manpower_enquiries
for insert
with check (auth.uid() = user_id);

-- SELECT: Users can view their own enquiries
create policy "Users can view their own enquiries"
on public.manpower_enquiries
for select
using (auth.uid() = user_id);

-- UPDATE: Users can update their own enquiries
create policy "Users can update their own enquiries"
on public.manpower_enquiries
for update
using (auth.uid() = user_id);

-- DELETE: Users can delete their own enquiries
create policy "Users can delete their own enquiries"
on public.manpower_enquiries
for delete
using (auth.uid() = user_id);
