-- Vehicle Management System Database Schema
-- For INDUS ERP CORE - Fire Tender/Vehicle Management Module

-- ==============================================
-- Table: vehicles_master
-- Purpose: Master database of all vehicles
-- ==============================================
CREATE TABLE IF NOT EXISTS vehicles_master (
    id bigint generated by default as identity primary key,
    vehicle_type text not null, -- Fire Tender, SUV, Car, Bike, Command Post, etc.
    registration_number text not null unique,
    chassis_number text,
    engine_number text,
    make text not null,
    model text not null,
    year_of_manufacture integer,
    date_of_purchase date,
    date_of_commissioning date,
    assigned_location text,
    assigned_site text,
    assigned_department text,
    assigned_driver_id uuid references auth.users(id),
    vehicle_status text not null default 'Available', -- Available, On Duty, Under Maintenance, Out for Repair, Rented, Decommissioned
    current_odometer_reading numeric default 0,
    last_service_date date,
    next_service_due date,
    remarks text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id) -- 🔑 link to Supabase Auth user
);

-- Enable Row Level Security
ALTER TABLE vehicles_master ENABLE ROW LEVEL SECURITY;

-- RLS Policies for vehicles_master
CREATE POLICY "Users can insert their own vehicles"
    ON vehicles_master FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own vehicles"
    ON vehicles_master FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own vehicles"
    ON vehicles_master FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own vehicles"
    ON vehicles_master FOR DELETE
    USING (auth.uid() = user_id);

-- ==============================================
-- Table: vehicle_documents
-- Purpose: Store vehicle documents with expiry tracking
-- ==============================================
CREATE TABLE IF NOT EXISTS vehicle_documents (
    id bigint generated by default as identity primary key,
    vehicle_id bigint not null references vehicles_master(id) on delete cascade,
    document_type text not null, -- RC, Insurance, Pollution Certificate, Fitness Certificate, Permit, AMC
    document_number text,
    issue_date date,
    expiry_date date not null,
    provider text, -- Insurance provider, issuing authority
    premium_amount numeric,
    file_url text, -- URL to uploaded document
    alert_status text default 'Active', -- Active, Warning, Expired
    remarks text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);

-- Enable Row Level Security
ALTER TABLE vehicle_documents ENABLE ROW LEVEL SECURITY;

-- RLS Policies for vehicle_documents
CREATE POLICY "Users can insert their own vehicle documents"
    ON vehicle_documents FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own vehicle documents"
    ON vehicle_documents FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own vehicle documents"
    ON vehicle_documents FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own vehicle documents"
    ON vehicle_documents FOR DELETE
    USING (auth.uid() = user_id);

-- ==============================================
-- Table: vehicle_maintenance
-- Purpose: Track maintenance history and service records
-- ==============================================
CREATE TABLE IF NOT EXISTS vehicle_maintenance (
    id bigint generated by default as identity primary key,
    vehicle_id bigint not null references vehicles_master(id) on delete cascade,
    service_date date not null,
    vendor text not null,
    service_type text, -- Regular Service, Repair, AMC Service, Emergency Repair
    cost numeric not null,
    odometer_reading numeric,
    nature_of_repair text,
    parts_replaced text,
    next_service_due date,
    remarks text,
    attachment_url text, -- Service receipt/invoice
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);

-- Enable Row Level Security
ALTER TABLE vehicle_maintenance ENABLE ROW LEVEL SECURITY;

-- RLS Policies for vehicle_maintenance
CREATE POLICY "Users can insert their own vehicle maintenance"
    ON vehicle_maintenance FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own vehicle maintenance"
    ON vehicle_maintenance FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own vehicle maintenance"
    ON vehicle_maintenance FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own vehicle maintenance"
    ON vehicle_maintenance FOR DELETE
    USING (auth.uid() = user_id);

-- ==============================================
-- Table: vehicle_trips
-- Purpose: Track vehicle usage and trips
-- ==============================================
CREATE TABLE IF NOT EXISTS vehicle_trips (
    id bigint generated by default as identity primary key,
    vehicle_id bigint not null references vehicles_master(id) on delete cascade,
    trip_purpose text not null, -- Official Duty, Rental, Site Visit, Logistics, Training, Demo, Client Delivery
    issued_to_name text not null,
    issued_to_department text,
    issued_to_contact text,
    start_date_time timestamptz not null,
    end_date_time timestamptz,
    origin_location text,
    destination_location text,
    odometer_start numeric,
    odometer_end numeric,
    fuel_added numeric default 0,
    fuel_cost numeric default 0,
    trip_status text default 'Active', -- Active, Completed, Cancelled
    approved_by text,
    approval_date timestamptz,
    remarks text,
    digital_signature_url text,
    attachments text[], -- Array of attachment URLs
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);

-- Enable Row Level Security
ALTER TABLE vehicle_trips ENABLE ROW LEVEL SECURITY;

-- RLS Policies for vehicle_trips
CREATE POLICY "Users can insert their own vehicle trips"
    ON vehicle_trips FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own vehicle trips"
    ON vehicle_trips FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own vehicle trips"
    ON vehicle_trips FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own vehicle trips"
    ON vehicle_trips FOR DELETE
    USING (auth.uid() = user_id);

-- ==============================================
-- Table: drivers
-- Purpose: Driver/Employee information for vehicle assignment
-- ==============================================
CREATE TABLE IF NOT EXISTS drivers (
    id bigint generated by default as identity primary key,
    employee_id text unique,
    full_name text not null,
    contact_number text,
    email text,
    license_number text,
    license_type text, -- LMV, HMV, Motorcycle, etc.
    license_expiry_date date,
    department text,
    designation text,
    is_active boolean default true,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id)
);

-- Enable Row Level Security
ALTER TABLE drivers ENABLE ROW LEVEL SECURITY;

-- RLS Policies for drivers
CREATE POLICY "Users can insert their own drivers"
    ON drivers FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own drivers"
    ON drivers FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own drivers"
    ON drivers FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own drivers"
    ON drivers FOR DELETE
    USING (auth.uid() = user_id);

-- ==============================================
-- Indexes for Performance
-- ==============================================

-- Indexes for vehicles_master
CREATE INDEX IF NOT EXISTS idx_vehicles_master_registration ON vehicles_master(registration_number);
CREATE INDEX IF NOT EXISTS idx_vehicles_master_status ON vehicles_master(vehicle_status);
CREATE INDEX IF NOT EXISTS idx_vehicles_master_type ON vehicles_master(vehicle_type);
CREATE INDEX IF NOT EXISTS idx_vehicles_master_user_id ON vehicles_master(user_id);

-- Indexes for vehicle_documents
CREATE INDEX IF NOT EXISTS idx_vehicle_documents_vehicle_id ON vehicle_documents(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_vehicle_documents_expiry ON vehicle_documents(expiry_date);
CREATE INDEX IF NOT EXISTS idx_vehicle_documents_type ON vehicle_documents(document_type);
CREATE INDEX IF NOT EXISTS idx_vehicle_documents_alert ON vehicle_documents(alert_status);

-- Indexes for vehicle_maintenance
CREATE INDEX IF NOT EXISTS idx_vehicle_maintenance_vehicle_id ON vehicle_maintenance(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_vehicle_maintenance_date ON vehicle_maintenance(service_date);
CREATE INDEX IF NOT EXISTS idx_vehicle_maintenance_next_due ON vehicle_maintenance(next_service_due);

-- Indexes for vehicle_trips
CREATE INDEX IF NOT EXISTS idx_vehicle_trips_vehicle_id ON vehicle_trips(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_vehicle_trips_status ON vehicle_trips(trip_status);
CREATE INDEX IF NOT EXISTS idx_vehicle_trips_start_date ON vehicle_trips(start_date_time);
CREATE INDEX IF NOT EXISTS idx_vehicle_trips_purpose ON vehicle_trips(trip_purpose);

-- Indexes for drivers
CREATE INDEX IF NOT EXISTS idx_drivers_employee_id ON drivers(employee_id);
CREATE INDEX IF NOT EXISTS idx_drivers_active ON drivers(is_active);

-- ==============================================
-- Functions for Alert Management
-- ==============================================

-- Function to update document alert status based on expiry date
CREATE OR REPLACE FUNCTION update_document_alerts()
RETURNS void AS $$
BEGIN
    UPDATE vehicle_documents 
    SET alert_status = CASE 
        WHEN expiry_date < CURRENT_DATE THEN 'Expired'
        WHEN expiry_date <= CURRENT_DATE + INTERVAL '30 days' THEN 'Warning'
        ELSE 'Active'
    END
    WHERE user_id = auth.uid();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get vehicles with upcoming document expiries
CREATE OR REPLACE FUNCTION get_upcoming_expiries(days_ahead integer DEFAULT 30)
RETURNS TABLE (
    vehicle_id bigint,
    registration_number text,
    document_type text,
    expiry_date date,
    days_remaining integer
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        vd.vehicle_id,
        vm.registration_number,
        vd.document_type,
        vd.expiry_date,
        (vd.expiry_date - CURRENT_DATE)::integer as days_remaining
    FROM vehicle_documents vd
    JOIN vehicles_master vm ON vd.vehicle_id = vm.id
    WHERE vd.expiry_date <= CURRENT_DATE + (days_ahead || ' days')::interval
    AND vd.user_id = auth.uid()
    ORDER BY vd.expiry_date ASC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==============================================
-- Comments for Documentation
-- ==============================================

COMMENT ON TABLE vehicles_master IS 'Master database of all vehicles with complete details';
COMMENT ON TABLE vehicle_documents IS 'Vehicle documents with expiry tracking and alerts';
COMMENT ON TABLE vehicle_maintenance IS 'Maintenance history and service records';
COMMENT ON TABLE vehicle_trips IS 'Vehicle usage tracking and trip management';
COMMENT ON TABLE drivers IS 'Driver/Employee information for vehicle assignment';

COMMENT ON COLUMN vehicles_master.vehicle_status IS 'Current operational status of the vehicle';
COMMENT ON COLUMN vehicle_documents.alert_status IS 'Alert status based on expiry date proximity';
COMMENT ON COLUMN vehicle_trips.trip_status IS 'Current status of the trip (Active/Completed/Cancelled)';
COMMENT ON COLUMN drivers.is_active IS 'Whether the driver is currently active and available';

