/**
 * Auto-discovered API catalog (read-only codebase scan).
 * Generated from static analysis of frontend, server, and Supabase Edge Functions.
 * Duplicate endpoints are consolidated; callLocations lists every reference found.
 */

export const DISCOVERY_SCAN_META = {
  scannedAt: "2026-07-13",
  scope: ["src/**", "server/**", "supabase/functions/**"],
  methods: ["REST", "RPC", "Edge Functions", "WebSocket", "env-configured URLs"],
};

/** @typedef {Object} DiscoveredApiEntry
 * @property {string} id
 * @property {string} name
 * @property {string} description
 * @property {'internal'|'external'} type
 * @property {string} category
 * @property {string} environment
 * @property {string} module
 * @property {string|null} serviceOwner
 * @property {string} endpoint
 * @property {string} httpMethod
 * @property {string} authType
 * @property {string} checkKey
 * @property {number} degradedThresholdMs
 * @property {string[]} sourceFiles
 * @property {string[]} callLocations
 */

/** @type {DiscoveredApiEntry[]} */
export const DISCOVERED_APIS = [
  {
    id: "erp-node-health",
    name: "ERP Node API (Health)",
    description: "Express backend health probe — confirms API process and Supabase env wiring",
    type: "internal",
    category: "Core Backend",
    environment: "production",
    module: "Platform",
    serviceOwner: "IT/IS",
    endpoint: "/api/health",
    httpMethod: "GET",
    authType: "none",
    checkKey: "node_health",
    degradedThresholdMs: 2000,
    sourceFiles: ["server/index.js", "src/lib/apiBase.js"],
    callLocations: ["server/index.js:782", "src/lib/apiBase.js:46", "src/App.jsx (startup check)"],
  },
  {
    id: "admin-attendance-status",
    name: "Attendance Integration Status",
    description: "eTimeOffice proxy configuration status (no punch data)",
    type: "internal",
    category: "HR Integrations",
    environment: "production",
    module: "Admin / HR",
    serviceOwner: "HR",
    endpoint: "/api/admin/attendance/status",
    httpMethod: "GET",
    authType: "none",
    checkKey: "node_get",
    degradedThresholdMs: 3000,
    sourceFiles: ["server/index.js", "src/lib/apiBase.js"],
    callLocations: ["server/index.js:942", "src/lib/apiBase.js:136", "src/pages/adminOperations/employee/EmployeeAdminPages.jsx"],
  },
  {
    id: "admin-attendance-punches",
    name: "Attendance Punch Download",
    description: "Proxied eTimeOffice punch fetch for attendance register",
    type: "internal",
    category: "HR Integrations",
    environment: "production",
    module: "Admin / HR",
    serviceOwner: "HR",
    endpoint: "/api/admin/attendance/punches",
    httpMethod: "GET",
    authType: "bearer_jwt",
    checkKey: "node_auth_probe_get",
    degradedThresholdMs: 5000,
    sourceFiles: ["server/index.js", "server/attendanceEtime.js", "src/pages/adminOperations/employee/EmployeeAdminPages.jsx"],
    callLocations: ["server/index.js:969", "src/pages/adminOperations/employee/EmployeeAdminPages.jsx:476"],
  },
  {
    id: "admin-attendance-sync",
    name: "Attendance Sync Job",
    description: "Triggers eTimeOffice → Supabase punch sync",
    type: "internal",
    category: "HR Integrations",
    environment: "production",
    module: "Admin / HR",
    serviceOwner: "HR",
    endpoint: "/api/admin/attendance/sync",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "node_auth_probe_post",
    degradedThresholdMs: 8000,
    sourceFiles: ["server/index.js", "server/attendanceEtime.js"],
    callLocations: ["server/index.js:1021"],
  },
  {
    id: "admin-profile-update",
    name: "Admin Profile Update API",
    description: "Server-side profile save (service role); fallback for User Management",
    type: "internal",
    category: "User Management",
    environment: "production",
    module: "User Management",
    serviceOwner: "IT/IS",
    endpoint: "/api/admin/update-profile",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "node_auth_probe_post",
    degradedThresholdMs: 4000,
    sourceFiles: ["server/index.js", "server/adminProfileApi.js", "src/lib/userManagementApi.js"],
    callLocations: ["server/index.js:799", "src/lib/userManagementApi.js:197"],
  },
  {
    id: "admin-create-user",
    name: "Admin Create User API",
    description: "Server-side user + profile bootstrap",
    type: "internal",
    category: "User Management",
    environment: "production",
    module: "User Management",
    serviceOwner: "IT/IS",
    endpoint: "/api/admin/create-user",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "node_auth_probe_post",
    degradedThresholdMs: 5000,
    sourceFiles: ["server/index.js", "server/adminCreateUserApi.js", "src/lib/userManagementCreateApi.js"],
    callLocations: ["server/index.js:831", "src/lib/userManagementCreateApi.js:58"],
  },
  {
    id: "admin-bulk-users",
    name: "Admin Bulk User Operations",
    description: "Bulk create/delete users via Node API (Edge Function fallback in client)",
    type: "internal",
    category: "User Management",
    environment: "production",
    module: "User Management",
    serviceOwner: "IT/IS",
    endpoint: "/api/admin/bulk-create-users, /api/admin/bulk-delete-users",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "node_auth_probe_post_bulk",
    degradedThresholdMs: 8000,
    sourceFiles: ["server/index.js", "src/lib/userManagementBulkApi.js"],
    callLocations: ["server/index.js:864", "server/index.js:896", "src/lib/userManagementBulkApi.js"],
  },
  {
    id: "billing-einvoice-proxy",
    name: "E-Invoice / IRN Proxy API",
    description: "Node proxy to Whitebooks for IRN generate and cancel",
    type: "internal",
    category: "Billing",
    environment: "production",
    module: "Billing",
    serviceOwner: "Billing",
    endpoint: "/api/billing/e-invoice/generate, /api/billing/e-invoice/cancel",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "node_auth_probe_post_einvoice",
    degradedThresholdMs: 10000,
    sourceFiles: ["server/index.js", "src/services/eInvoiceApi.js"],
    callLocations: ["server/index.js:1056", "server/index.js:1237", "src/services/eInvoiceApi.js"],
  },
  {
    id: "software-subscriptions-r2",
    name: "Software Subscriptions R2 Storage",
    description: "Cloudflare R2 upload, presigned GET, and delete via Node proxy",
    type: "internal",
    category: "IT/IS",
    environment: "production",
    module: "IT/IS",
    serviceOwner: "IT/IS",
    endpoint: "/api/software-subscriptions/r2/*",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "node_auth_probe_post_r2_presign",
    degradedThresholdMs: 5000,
    sourceFiles: ["server/index.js", "src/pages/SoftwareSubscriptions.jsx"],
    callLocations: [
      "server/index.js:1277 (upload)",
      "server/index.js:1334 (presign-get)",
      "server/index.js:1354 (delete)",
      "src/pages/SoftwareSubscriptions.jsx",
    ],
  },
  {
    id: "fleet-r2-storage",
    name: "Fleet Management R2 Storage",
    description: "Fleet documents/drivers file storage via Cloudflare R2 proxy",
    type: "internal",
    category: "Operations",
    environment: "production",
    module: "Operations",
    serviceOwner: "Operations",
    endpoint: "/api/fleet/r2/upload, /api/fleet/r2/presign-get",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "node_auth_probe_post_fleet_presign",
    degradedThresholdMs: 5000,
    sourceFiles: ["server/index.js", "src/lib/fleetR2.js"],
    callLocations: ["server/index.js:1374", "server/index.js:1437", "src/lib/fleetR2.js"],
  },
  {
    id: "supabase-rest",
    name: "Supabase REST API",
    description: "PostgREST — all supabase.from() / schema table access across ERP modules",
    type: "external",
    category: "Data Platform",
    environment: "production",
    module: "Platform",
    serviceOwner: "IT/IS",
    endpoint: "{VITE_SUPABASE_URL}/rest/v1/",
    httpMethod: "GET",
    authType: "supabase_anon_jwt",
    checkKey: "supabase_rest",
    degradedThresholdMs: 2500,
    sourceFiles: ["src/lib/supabase.js", "src/services/*.js", "src/pages/**"],
    callLocations: [
      "Consolidated: billingApi, financeApi, payrollApi, projectsApi, amcApi, attendanceDaily, and 100+ page-level queries",
    ],
  },
  {
    id: "supabase-auth",
    name: "Supabase Auth API",
    description: "Authentication, session refresh, and password flows",
    type: "external",
    category: "Data Platform",
    environment: "production",
    module: "Platform",
    serviceOwner: "IT/IS",
    endpoint: "{VITE_SUPABASE_URL}/auth/v1/*",
    httpMethod: "GET",
    authType: "supabase_anon_key",
    checkKey: "supabase_auth_health",
    degradedThresholdMs: 2500,
    sourceFiles: ["src/lib/supabase.js", "src/lib/authSessionUtils.js", "src/contexts/AuthContext.jsx"],
    callLocations: ["src/lib/supabase.js:606", "src/lib/authSessionUtils.js:57", "src/lib/authSessionUtils.js:112"],
  },
  {
    id: "supabase-realtime",
    name: "Supabase Realtime (WebSocket)",
    description: "postgres_changes subscriptions when enabled",
    type: "external",
    category: "Data Platform",
    environment: "production",
    module: "Platform",
    serviceOwner: "IT/IS",
    endpoint: "wss://{project}.supabase.co/realtime/v1/websocket",
    httpMethod: "WebSocket",
    authType: "supabase_anon_key",
    checkKey: "supabase_realtime_ws",
    degradedThresholdMs: 5000,
    sourceFiles: ["src/lib/backendDiagnostics.js", "src/lib/supabaseConfig.js"],
    callLocations: ["src/lib/backendDiagnostics.js:24", "VITE_DISABLE_SUPABASE_REALTIME env"],
  },
  {
    id: "supabase-rpc",
    name: "Supabase Database RPC",
    description: "Postgres functions invoked via supabase.rpc()",
    type: "external",
    category: "Data Platform",
    environment: "production",
    module: "Platform",
    serviceOwner: "IT/IS",
    endpoint: "{VITE_SUPABASE_URL}/rest/v1/rpc/{function}",
    httpMethod: "POST",
    authType: "supabase_jwt",
    checkKey: "supabase_rest",
    degradedThresholdMs: 3000,
    sourceFiles: [
      "src/lib/leaveManagement.js",
      "src/lib/attendanceDaily.js",
      "server/adminProfileApi.js",
      "server/adminCreateUserApi.js",
      "supabase/functions/**",
    ],
    callLocations: [
      "recalculate_employee_leave_entitlements",
      "fetch_approved_tour_marks_for_register",
      "get_profile_role",
      "admin_save_profile",
      "admin_upsert_profile",
      "profile_employee_code_taken",
    ],
  },
  {
    id: "edge-login-check",
    name: "Edge Function: login-check",
    description: "Post-login authorization profile and module access",
    type: "internal",
    category: "Auth",
    environment: "production",
    module: "Platform",
    serviceOwner: "IT/IS",
    endpoint: "/functions/v1/login-check",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "supabase_edge_function",
    degradedThresholdMs: 4000,
    sourceFiles: ["supabase/functions/login-check/index.ts", "src/lib/loginFlow.js", "src/contexts/AuthContext.jsx"],
    callLocations: ["src/lib/loginFlow.js:76", "src/contexts/AuthContext.jsx:334"],
  },
  {
    id: "edge-admin-create-user",
    name: "Edge Function: admin-create-user",
    description: "User Management create user (Edge fallback)",
    type: "internal",
    category: "User Management",
    environment: "production",
    module: "User Management",
    serviceOwner: "IT/IS",
    endpoint: "/functions/v1/admin-create-user",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "supabase_edge_function_named",
    degradedThresholdMs: 5000,
    sourceFiles: ["supabase/functions/admin-create-user/index.ts", "src/lib/userManagementCreateApi.js"],
    callLocations: ["src/lib/userManagementCreateApi.js:86"],
  },
  {
    id: "edge-admin-update-profile",
    name: "Edge Function: admin-update-profile",
    description: "User Management profile save (Edge path)",
    type: "internal",
    category: "User Management",
    environment: "production",
    module: "User Management",
    serviceOwner: "IT/IS",
    endpoint: "/functions/v1/admin-update-profile",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "supabase_edge_function_named",
    degradedThresholdMs: 5000,
    sourceFiles: ["supabase/functions/admin-update-profile/index.ts", "src/lib/userManagementApi.js"],
    callLocations: ["src/lib/userManagementApi.js:220"],
  },
  {
    id: "edge-admin-delete-user",
    name: "Edge Function: admin-delete-user",
    description: "User Management delete user",
    type: "internal",
    category: "User Management",
    environment: "production",
    module: "User Management",
    serviceOwner: "IT/IS",
    endpoint: "/functions/v1/admin-delete-user",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "supabase_edge_function_named",
    degradedThresholdMs: 5000,
    sourceFiles: ["supabase/functions/admin-delete-user/index.ts", "src/pages/UserManagement.jsx"],
    callLocations: ["src/pages/UserManagement.jsx:634"],
  },
  {
    id: "edge-admin-bulk-create",
    name: "Edge Function: admin-bulk-create-users",
    description: "Bulk user import via Edge Function",
    type: "internal",
    category: "User Management",
    environment: "production",
    module: "User Management",
    serviceOwner: "IT/IS",
    endpoint: "/functions/v1/admin-bulk-create-users",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "supabase_edge_function_named",
    degradedThresholdMs: 8000,
    sourceFiles: ["supabase/functions/admin-bulk-create-users/index.ts", "src/lib/userManagementBulkApi.js"],
    callLocations: ["src/lib/userManagementBulkApi.js"],
  },
  {
    id: "edge-admin-bulk-delete",
    name: "Edge Function: admin-bulk-delete-users",
    description: "Bulk user delete via Edge Function",
    type: "internal",
    category: "User Management",
    environment: "production",
    module: "User Management",
    serviceOwner: "IT/IS",
    endpoint: "/functions/v1/admin-bulk-delete-users",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "supabase_edge_function_named",
    degradedThresholdMs: 8000,
    sourceFiles: ["supabase/functions/admin-bulk-delete-users/index.ts", "src/lib/userManagementBulkApi.js"],
    callLocations: ["src/lib/userManagementBulkApi.js"],
  },
  {
    id: "edge-admin-list-profiles",
    name: "Edge Function: admin-list-profiles",
    description: "User Management profile listing (deployed; client may use direct REST)",
    type: "internal",
    category: "User Management",
    environment: "production",
    module: "User Management",
    serviceOwner: "IT/IS",
    endpoint: "/functions/v1/admin-list-profiles",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "supabase_edge_function_named",
    degradedThresholdMs: 5000,
    sourceFiles: ["supabase/functions/admin-list-profiles/index.ts"],
    callLocations: ["supabase/functions/admin-list-profiles/index.ts (deployed)"],
  },
  {
    id: "edge-access-check",
    name: "Edge Function: access-check",
    description: "Module access verification Edge Function",
    type: "internal",
    category: "Auth",
    environment: "production",
    module: "Platform",
    serviceOwner: "IT/IS",
    endpoint: "/functions/v1/access-check",
    httpMethod: "POST",
    authType: "bearer_jwt",
    checkKey: "supabase_edge_function_named",
    degradedThresholdMs: 4000,
    sourceFiles: ["supabase/functions/access-check/index.ts"],
    callLocations: ["supabase/functions/access-check/index.ts (deployed)"],
  },
  {
    id: "external-etimeoffice",
    name: "eTimeOffice Attendance API",
    description: "Third-party punch/attendance provider (server-side proxy only)",
    type: "external",
    category: "HR Integrations",
    environment: "production",
    module: "Admin / HR",
    serviceOwner: "HR",
    endpoint: "https://api.etimeoffice.com/api/{endpoint}",
    httpMethod: "GET",
    authType: "provider_credentials",
    checkKey: "indirect_etime_status",
    degradedThresholdMs: 8000,
    sourceFiles: ["server/attendanceEtime.js", ".env.server.example"],
    callLocations: ["server/attendanceEtime.js:301", "ETIME_BASE_URL env"],
  },
  {
    id: "external-whitebooks",
    name: "Whitebooks E-Invoice (IRP) API",
    description: "GST e-invoice IRN generation provider",
    type: "external",
    category: "Billing",
    environment: "production",
    module: "Billing",
    serviceOwner: "Billing",
    endpoint: "https://api.whitebooks.in/*",
    httpMethod: "POST",
    authType: "whitebooks_session",
    checkKey: "indirect_whitebooks",
    degradedThresholdMs: 10000,
    sourceFiles: ["server/index.js", "src/services/eInvoiceApi.js", ".env.server.example"],
    callLocations: ["server/index.js:387", "src/services/eInvoiceApi.js:649"],
  },
  {
    id: "external-open-exchange-rates",
    name: "Open Exchange Rates API",
    description: "USD/INR FX rates for software subscription costing",
    type: "external",
    category: "Third-party Services",
    environment: "production",
    module: "IT/IS",
    serviceOwner: "IT/IS",
    endpoint: "https://open.er-api.com/v6/latest/USD",
    httpMethod: "GET",
    authType: "none",
    checkKey: "external_get",
    degradedThresholdMs: 4000,
    sourceFiles: ["src/pages/SoftwareSubscriptions.jsx"],
    callLocations: ["src/pages/SoftwareSubscriptions.jsx:34", "src/pages/SoftwareSubscriptions.jsx:267"],
  },
];
