-- Fleet management: full vehicle_master columns, child tables, RLS (matches src/pages/fireTenderVehicle/*)

-- ---------------------------------------------------------------------------
-- Vehicle master: columns expected by VehicleMaster.jsx
-- ---------------------------------------------------------------------------
ALTER TABLE operations_fire_tender_vehicle_master
  ADD COLUMN IF NOT EXISTS vehicle_category text DEFAULT 'in-house',
  ADD COLUMN IF NOT EXISTS vehicle_name text,
  ADD COLUMN IF NOT EXISTS chassis_number text,
  ADD COLUMN IF NOT EXISTS chassis_model text,
  ADD COLUMN IF NOT EXISTS engine_number text,
  ADD COLUMN IF NOT EXISTS year_of_manufacture integer,
  ADD COLUMN IF NOT EXISTS date_of_manufacture text,
  ADD COLUMN IF NOT EXISTS date_of_registration date,
  ADD COLUMN IF NOT EXISTS registry_validity_date date,
  ADD COLUMN IF NOT EXISTS date_of_commissioning date,
  ADD COLUMN IF NOT EXISTS date_of_purchase date,
  ADD COLUMN IF NOT EXISTS ownership_type text,
  ADD COLUMN IF NOT EXISTS owner_name text,
  ADD COLUMN IF NOT EXISTS emission_norms text,
  ADD COLUMN IF NOT EXISTS fuel_type text,
  ADD COLUMN IF NOT EXISTS financier text,
  ADD COLUMN IF NOT EXISTS pump_make_brand text,
  ADD COLUMN IF NOT EXISTS pump_model_number text,
  ADD COLUMN IF NOT EXISTS pump_serial_number text,
  ADD COLUMN IF NOT EXISTS pto_type text,
  ADD COLUMN IF NOT EXISTS water_tank_capacity numeric,
  ADD COLUMN IF NOT EXISTS foam_tank_capacity numeric,
  ADD COLUMN IF NOT EXISTS assigned_location text,
  ADD COLUMN IF NOT EXISTS assigned_site text,
  ADD COLUMN IF NOT EXISTS assigned_department text,
  ADD COLUMN IF NOT EXISTS current_odometer_reading numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_service_date date,
  ADD COLUMN IF NOT EXISTS next_service_due date,
  ADD COLUMN IF NOT EXISTS remarks text;

UPDATE operations_fire_tender_vehicle_master
SET vehicle_category = 'in-house'
WHERE vehicle_category IS NULL;

-- ---------------------------------------------------------------------------
-- Vehicle trips (VehicleTrips.jsx)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS operations_fire_tender_vehicle_trips (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_type text,
  vehicle_id bigint REFERENCES operations_fire_tender_vehicle_master(id) ON DELETE SET NULL,
  trip_purpose text,
  issued_to_name text,
  issued_to_department text,
  issued_to_contact text,
  start_date_time timestamptz,
  end_date_time timestamptz,
  origin_location text,
  destination_location text,
  odometer_start numeric,
  odometer_end numeric,
  fuel_added numeric DEFAULT 0,
  fuel_cost numeric DEFAULT 0,
  trip_status text NOT NULL DEFAULT 'Active',
  approved_by text,
  approval_date timestamptz,
  remarks text,
  driver_name text,
  deployment_location text,
  site_name text,
  date_of_mobilisation date,
  km_at_mobilisation_out numeric,
  km_at_demobilisation_in numeric,
  contract_start_date date,
  contract_end_date date,
  notes text,
  responsible_person text,
  site_visit_location text,
  number_of_passengers integer,
  visit_date date,
  visit_duration_days integer,
  departments_allotted jsonb,
  expense_attachments jsonb,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_operations_fire_tender_vehicle_trips_user_id
  ON operations_fire_tender_vehicle_trips(user_id);
CREATE INDEX IF NOT EXISTS idx_operations_fire_tender_vehicle_trips_vehicle_id
  ON operations_fire_tender_vehicle_trips(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_operations_fire_tender_vehicle_trips_status
  ON operations_fire_tender_vehicle_trips(trip_status);

-- ---------------------------------------------------------------------------
-- Vehicle documents (VehicleDocuments.jsx)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS operations_fire_tender_vehicle_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id bigint NOT NULL REFERENCES operations_fire_tender_vehicle_master(id) ON DELETE CASCADE,
  document_type text,
  document_number text,
  issue_date date,
  expiry_date date,
  provider text,
  premium_amount numeric,
  file_url text,
  remarks text,
  alert_status text DEFAULT 'Active',
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_operations_fire_tender_vehicle_documents_user_id
  ON operations_fire_tender_vehicle_documents(user_id);
CREATE INDEX IF NOT EXISTS idx_operations_fire_tender_vehicle_documents_vehicle_id
  ON operations_fire_tender_vehicle_documents(vehicle_id);

-- ---------------------------------------------------------------------------
-- Vehicle maintenance (VehicleMaintenance.jsx)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS operations_fire_tender_vehicle_maintenance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id bigint NOT NULL REFERENCES operations_fire_tender_vehicle_master(id) ON DELETE CASCADE,
  service_date date,
  vendor text,
  service_type text,
  cost numeric DEFAULT 0,
  odometer_reading numeric,
  nature_of_repair text,
  parts_replaced text,
  next_service_due date,
  remarks text,
  attachment_url text,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_operations_fire_tender_vehicle_maintenance_user_id
  ON operations_fire_tender_vehicle_maintenance(user_id);
CREATE INDEX IF NOT EXISTS idx_operations_fire_tender_vehicle_maintenance_vehicle_id
  ON operations_fire_tender_vehicle_maintenance(vehicle_id);

-- ---------------------------------------------------------------------------
-- Row level security (authenticated users: own rows by user_id)
-- ---------------------------------------------------------------------------
ALTER TABLE operations_fire_tender_vehicle_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations_fire_tender_vehicle_drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations_fire_tender_vehicle_trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations_fire_tender_vehicle_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations_fire_tender_vehicle_maintenance ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "fleet_vehicle_master_own" ON operations_fire_tender_vehicle_master;
CREATE POLICY "fleet_vehicle_master_own" ON operations_fire_tender_vehicle_master
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "fleet_vehicle_drivers_own" ON operations_fire_tender_vehicle_drivers;
CREATE POLICY "fleet_vehicle_drivers_own" ON operations_fire_tender_vehicle_drivers
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "fleet_vehicle_trips_own" ON operations_fire_tender_vehicle_trips;
CREATE POLICY "fleet_vehicle_trips_own" ON operations_fire_tender_vehicle_trips
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "fleet_vehicle_documents_own" ON operations_fire_tender_vehicle_documents;
CREATE POLICY "fleet_vehicle_documents_own" ON operations_fire_tender_vehicle_documents
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "fleet_vehicle_maintenance_own" ON operations_fire_tender_vehicle_maintenance;
CREATE POLICY "fleet_vehicle_maintenance_own" ON operations_fire_tender_vehicle_maintenance
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
